"use client";
import Link from "next/link";
import { useEffect,useState,useCallback,type FormEvent } from "react";
import { thb,thaiToday } from "@/lib/partner-display";
import type { PartnerRate,commissionStatement } from "@/lib/partner-portal";
import { VEHICLES } from "@/lib/vehicles";
type Partner={id:string;agency_name:string;email:string;status:string;partner_kind:string|null;billing_name:string|null;billing_address:string|null;tax_id:string|null;commission_bps:number|null};
const box="rounded-2xl border bg-white p-5",field="mt-1 w-full rounded-xl border p-3",button="rounded-full bg-orange-500 px-5 py-3 font-semibold text-white disabled:opacity-50";
export function PartnerContracts(){
 const [partners,setPartners]=useState<Partner[]>([]),[id,setId]=useState(""),[rates,setRates]=useState<PartnerRate[]>([]),[invoices,setInvoices]=useState<{id:string;booking_reference:string;amount_minor:number}[]>([]),[period,setPeriod]=useState(thaiToday().slice(0,7)),[statement,setStatement]=useState<Awaited<ReturnType<typeof commissionStatement>>|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const partner=partners.find(p=>p.id===id);
 const load=useCallback(async(agencyId:string,month:string)=>{const r=await fetch(`/api/admin/partners?agencyId=${encodeURIComponent(agencyId)}&period=${month}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setPartners(d.partners);setRates(d.rates);setInvoices(d.invoices);setStatement(d.statement);},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load("",thaiToday().slice(0,7)).catch(e=>setMessage(e.message)),0);return()=>clearTimeout(timer);},[load]);
 async function save(action:string,data:unknown){setBusy(true);setMessage("");try{const r=await fetch("/api/admin/partners",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({agencyId:id,action,data})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load(id,period);setMessage("Saved.");}catch(e){setMessage(e instanceof Error?e.message:"Could not save.");}finally{setBusy(false);}}
 function profileSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);void save("profile",{partnerKind:d.get("kind"),billingName:d.get("name"),billingAddress:d.get("address"),taxId:d.get("taxId"),commissionBps:Math.round(Number(d.get("commission"))*100)});}
 function rateSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);void save("rate",{label:d.get("label"),pickup:d.get("pickup"),dropoff:d.get("dropoff"),vehicle:d.get("vehicle"),serviceType:d.get("service"),bookedHours:d.get("hours")?Number(d.get("hours")):undefined,priceMinor:Math.round(Number(d.get("price"))*100),validFrom:d.get("from"),validUntil:d.get("until")});}
 return <main className="mx-auto max-w-6xl space-y-6 p-5 pb-24 sm:p-8"><header><h1 className="text-3xl font-bold">Hotel & agency contracts</h1><p className="mt-2 text-slate-500">Configure approved partners, rate cards, commissions and issued invoices.</p><Link href="/admin/agencies" className="mt-3 inline-block font-semibold text-orange-700 underline">Review partner applications</Link></header><label className="block">Partner<select value={id} onChange={e=>{setId(e.target.value);setMessage("");void load(e.target.value,period).catch(err=>setMessage(err.message));}} className={field}><option value="">Choose an approved partner</option>{partners.filter(p=>p.status==="approved").map(p=><option key={p.id} value={p.id}>{p.agency_name} · {p.email}</option>)}</select></label><p role="status" className="text-sm text-orange-800">{message}</p>
  {partner&&<>
   <form key={id} onSubmit={profileSubmit} className={`${box} grid gap-4 sm:grid-cols-2`}><h2 className="text-xl font-bold sm:col-span-2">Billing & commission agreement</h2><label>Partner type<select name="kind" defaultValue={partner.partner_kind??"agency"} className={field}><option value="agency">Agency</option><option value="hotel">Hotel / concierge</option></select></label><label>Billing name<input name="name" required maxLength={200} defaultValue={partner.billing_name||partner.agency_name} className={field}/></label><label className="sm:col-span-2">Billing address<textarea name="address" rows={3} maxLength={1000} defaultValue={partner.billing_address??""} className={field}/></label><label>Tax / company ID<input name="taxId" maxLength={80} defaultValue={partner.tax_id??""} className={field}/></label><label>Commission %<input name="commission" type="number" min={0} max={100} step="0.01" required defaultValue={(partner.commission_bps??0)/100} className={field}/></label><p className="text-sm text-slate-500 sm:col-span-2">Applies to new requests and bookings only. Existing agreements keep their snapshot. Commission excludes extras and is reduced by refunds.</p><button disabled={busy} className={`${button} justify-self-start`}>Save agreement</button></form>
   <section className={box}><h2 className="text-xl font-bold">Negotiated rates</h2><p className="mt-2 text-sm text-slate-500">One-way base fare, excluding extras. Disable and replace a rate to revise it. Existing bookings retain their accepted terms.</p><ul className="my-4 divide-y">{rates.map(r=><li key={r.id} className="flex flex-wrap justify-between gap-3 py-3 text-sm"><div><b>{r.label}</b> · {thb(r.price_minor)} · {r.active?"Active":"Disabled"}<p>{r.pickup} → {r.dropoff} · {r.valid_from}–{r.valid_until}</p></div>{Boolean(r.active)&&<button disabled={busy} onClick={()=>void save("disable_rate",{id:r.id})} className="font-bold text-orange-700">Disable</button>}</li>)}</ul><form onSubmit={rateSubmit} className="grid gap-3 sm:grid-cols-2"><label>Rate label<input name="label" required maxLength={120} className={field}/></label><label>Service<select name="service" className={field}><option value="transfer">Transfer</option><option value="hourly">Hourly</option><option value="tour">Tour</option></select></label><label>Pickup<input name="pickup" required maxLength={300} className={field}/></label><label>Destination / itinerary<input name="dropoff" required maxLength={300} className={field}/></label><label>Vehicle<select name="vehicle" className={field}>{Object.entries(VEHICLES).map(([key,v])=><option key={key} value={key}>{v.name}</option>)}</select></label><label>Hourly duration (optional)<input name="hours" type="number" min={3} max={24} step={1} className={field}/></label><label>Base fare THB<input name="price" required type="number" min="0.01" max={1000000} step="0.01" className={field}/></label><label>Valid from<input name="from" required type="date" defaultValue={thaiToday()} className={field}/></label><label>Valid until<input name="until" required type="date" className={field}/></label><button disabled={busy} className={`${button} self-end justify-self-start`}>Add rate</button></form></section>
   <section className={box}><h2 className="text-xl font-bold">Invoices</h2><p className="mt-2 text-sm text-slate-500">Requires configured issuer name/address and partner billing details. Commercial invoices retain issued values; refunds need finance adjustments.</p><form onSubmit={e=>{e.preventDefault();void save("invoice",{reference:new FormData(e.currentTarget).get("reference")});}} className="my-4 flex flex-wrap gap-3"><label><span className="sr-only">Booking reference</span><input name="reference" required maxLength={30} placeholder="Partner booking reference" className={field}/></label><button disabled={busy} className={button}>Issue invoice</button></form>{invoices.map(i=><a key={i.id} className="block border-t py-3 text-sm font-semibold text-orange-700" href={`/api/agency/invoices/${i.id}`} target="_blank" rel="noreferrer">{i.booking_reference} · {thb(i.amount_minor)} · Open invoice ↗</a>)}</section>
   <section className={box}><h2 className="text-xl font-bold">Commission settlement</h2><form className="my-4 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();void load(id,period).catch(err=>setMessage(err.message));}}><label><span className="sr-only">Statement month</span><input type="month" required value={period} onChange={e=>setPeriod(e.target.value)} className={field}/></label><button className="rounded-full border px-5 py-3 font-semibold">View statement</button></form>{statement&&<><p className="font-semibold">Earned {thb(statement.earnedMinor)} · Paid {thb(statement.paidMinor)} · Balance {thb(statement.balanceMinor)}</p><ul className="my-4 divide-y">{statement.rows.map(r=><li key={r.reference} className="flex justify-between py-2 text-sm"><span>{r.reference} · {r.status} · {r.payment_status}</span><b>{thb(r.commissionMinor)}</b></li>)}</ul><p className="text-sm text-slate-500">Record a payment already made outside this platform. This action does not transfer money. One recorded settlement per month; negative balances after refunds require an adjustment.</p><form className="mt-4 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();void save("payout",{period:statement.period,paymentReference:new FormData(e.currentTarget).get("paymentReference")});}}><label><span className="sr-only">Payment evidence reference</span><input name="paymentReference" required minLength={3} maxLength={150} placeholder="Bank / payment evidence reference" className={field}/></label><button disabled={busy||statement.balanceMinor<=0||Boolean(statement.payout)} className={button}>Record paid {thb(Math.max(0,statement.balanceMinor))}</button></form></>}</section>
  </>}
 </main>;
}
