"use client";
import { useEffect, useState, useCallback, type FormEvent } from "react";
type Staff={id:string;username:string;role:string;active:number;enrolled:number};
export default function StaffPage() {
 const [staff,setStaff]=useState<Staff[]>([]),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/admin/staff",{cache:"no-store"});const v=await r.json();if(r.ok)setStaff(v.staff);else setMessage(v.error);},[]);
 useEffect(()=>{const first=setTimeout(()=>void load(),0);return()=>clearTimeout(first);},[load]);
 async function action(body:Record<string,unknown>){const r=await fetch("/api/admin/staff",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const v=await r.json();setMessage(r.ok?"Saved.":v.error);await load();return r.ok;}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));if(await action({action:"create",...data}))form.reset();}
 return <main className="mx-auto max-w-3xl space-y-6 p-8"><h1 className="text-3xl font-bold">Staff access</h1><p>Individual accounts require authenticator MFA. Sessions expire after eight hours or 30 minutes idle.</p><form onSubmit={create} className="grid gap-3 rounded-xl border p-5"><h2 className="font-bold">Add staff</h2><input name="username" aria-label="Staff ID" placeholder="Staff ID" required pattern="[a-z0-9._-]{3,60}" className="border p-3"/><input name="email" type="email" aria-label="Email" placeholder="Email" required className="border p-3"/><input name="password" type="password" autoComplete="new-password" aria-label="Initial password" placeholder="Initial password (12+ characters)" required minLength={12} maxLength={200} className="border p-3"/><select name="role" aria-label="Role" className="border p-3">{["operations","finance","editor","support"].map(r=><option key={r}>{r}</option>)}</select><button className="rounded bg-orange-500 p-3 font-bold">Create account</button></form><p role="status">{message}</p>{staff.map(s=><div key={s.id} className="flex flex-wrap items-center gap-4 rounded border p-4"><strong>{s.username}</strong><span>{s.role} · {s.active?"Active":"Disabled"} · {s.enrolled?"MFA enrolled":"MFA required"}</span><button onClick={()=>void action({action:"revoke",id:s.id})} className="underline">Revoke sessions</button>{s.role!=="owner"&&s.active===1&&<button onClick={()=>void action({action:"disable",id:s.id})} className="underline">Disable</button>}</div>)}</main>;
}
