import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CarFront, Headphones, MapPin, ShieldCheck } from "lucide-react";
import { PublicFooter } from "@/components/public-footer";
import { Breadcrumbs, JsonLd, breadcrumbSchema, faqSchema } from "@/components/seo";
import { destinationRegions, destinations, SITE_URL } from "@/lib/public-content";

const crumbs=[{name:"Home",path:"/"},{name:"Destinations",path:"/destinations"}];
const faq=[
  {q:"Where in Thailand does Waydidi operate?",a:"Waydidi arranges private transfers around Bangkok, Pattaya, Hua Hin, Ayutthaya, Kanchanaburi, Phuket, Krabi, Koh Chang and Koh Kood, including airport pickups and long-distance trips between regions."},
  {q:"Is the vehicle shared with other passengers?",a:"No. Every Waydidi booking is one private vehicle for your group only, from your pickup to your drop-off."},
  {q:"Can I travel between two cities in one booking?",a:"Yes. Search your exact pickup and drop-off, such as a Bangkok hotel and a Pattaya resort, and one car covers the whole journey."},
  {q:"How is the price calculated?",a:"The price depends on your route and vehicle. You see it before you book, and it is recorded with your booking reference."},
];

export const metadata:Metadata={title:"Private Transfers & Airport Taxi in Thailand | Waydidi",description:"Explore Waydidi private transfers in Bangkok, Phuket, Krabi, Pattaya, Kanchanaburi, Koh Chang, Koh Kood, Ayutthaya and Hua Hin.",alternates:{canonical:`${SITE_URL}/destinations`},openGraph:{title:"Private Transfers & Airport Taxi in Thailand | Waydidi",url:`${SITE_URL}/destinations`,type:"website"}};

export default function DestinationsPage(){
  const list={"@context":"https://schema.org","@type":"ItemList",itemListElement:destinations.map((d,i)=>({"@type":"ListItem",position:i+1,name:`${d.name} private transfers`,url:`${SITE_URL}/destinations/${d.slug}`}))};
  return <main className="bg-white text-[#211726]">
  <JsonLd data={[breadcrumbSchema(crumbs),list,faqSchema(faq)]}/>
  <section className="mx-auto max-w-[1280px] px-5 pt-5 lg:px-8"><div className="grid overflow-hidden rounded-[30px] bg-[#211726] text-white lg:grid-cols-[1.05fr_.95fr]"><div className="p-7 sm:p-12 lg:p-16"><Breadcrumbs crumbs={crumbs} className="mb-8 text-white"/><p className="text-sm font-black uppercase tracking-[.18em] text-[#FF9E2F]">Waydidi destinations</p><h1 className="mt-4 text-4xl font-black leading-[.98] tracking-[-.045em] sm:text-6xl">Private rides across Thailand.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/75">Start at an airport, hotel, home or pier. Choose the place you are travelling to and book one private vehicle for the full route.</p><Link href="/#booking-search" className="mt-9 inline-flex items-center gap-2 rounded-full bg-[#FF8A05] px-6 py-4 font-black">Search your route <ArrowRight size={18}/></Link></div><div className="relative min-h-[330px] overflow-hidden bg-[#FF8A05]"><img src="/waydidi-transfer.png" alt="Waydidi private transfer in Thailand" className="absolute inset-0 h-full w-full object-cover"/></div></div></section>
  <section className="mx-auto max-w-[1180px] px-5 py-16"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-black uppercase tracking-[.18em] text-[#D96F00]">Choose a place</p><p className="mt-2 text-3xl font-black tracking-[-.035em] sm:text-5xl">Popular transfer regions</p></div><p className="max-w-md leading-7 text-slate-600">Use the cards to see useful routes, local pickup notes and the fastest way to start a booking.</p></div>{destinationRegions.map(region=><div key={region} className="mt-12"><h2 className="text-2xl font-black tracking-[-.02em]">{region}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{destinations.filter(d=>d.region===region).map(d=><a href={`/destinations/${d.slug}`} key={d.slug} className="group relative min-h-[260px] overflow-hidden rounded-[24px] p-6 text-white" style={{backgroundColor:d.color}}><div className="absolute -bottom-16 -right-10 size-48 rounded-full bg-white/8 transition group-hover:scale-110"/><div className="relative flex h-full flex-col"><span className="text-sm font-bold text-white/65">{d.kicker}</span><h3 className="mt-3 text-3xl font-black">{d.name}</h3><p className="mt-3 max-w-sm leading-7 text-white/75">{d.intro}</p><span className="mt-auto inline-flex items-center gap-2 pt-8 font-black text-[#FFB25A]">Explore transfers <ArrowRight size={17}/></span></div></a>)}</div></div>)}</section>
  <section className="bg-[#F5F6F8] py-16"><div className="mx-auto grid max-w-[1180px] gap-4 px-5 md:grid-cols-3"><Trust icon={CarFront} title="One private vehicle" text="No shared shuttle and no unnecessary vehicle changes."/><Trust icon={ShieldCheck} title="Clear booking record" text="Route, schedule, capacity and total stay attached to your reference."/><Trust icon={Headphones} title="Operational support" text="Help with pickups, changes and active journeys when you need it."/></div></section>
  <section className="mx-auto max-w-[860px] px-5 py-16"><h2 className="text-3xl font-black tracking-[-.035em] sm:text-4xl">Thailand transfer FAQ</h2><div className="mt-8 grid gap-3">{faq.map(f=><details key={f.q} className="rounded-2xl bg-[#F5F6F8] p-5"><summary className="cursor-pointer list-none font-black">{f.q}</summary><p className="mt-3 leading-7 text-slate-600">{f.a}</p></details>)}</div></section>
  <PublicFooter/>
</main>}
function Trust({icon:Icon,title,text}:{icon:typeof MapPin;title:string;text:string}){return <article className="rounded-[24px] bg-white p-6"><Icon className="text-[#FF8A05]"/><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-2 leading-7 text-slate-600">{text}</p></article>}
