import { migrationStatements } from './helpers/migrations.mjs';
import assert from 'node:assert/strict';
import {Miniflare} from 'miniflare';
import {createServer} from 'vite';
import {readFile,readdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {createHmac} from 'node:crypto';
const root=fileURLToPath(new URL('..',import.meta.url));
const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("test")}}',compatibilityDate:'2026-05-22',d1Databases:['DB']});
const d1=await mf.getD1Database('DB');
for(const name of (await readdir(root+'/drizzle')).filter(n=>n.endsWith('.sql')).sort()){
const statements=migrationStatements((await readFile(root+'/drizzle/'+name,'utf8'))).map(s=>s.trim()).filter(Boolean);
if(statements.length)await d1.batch(statements.map(s=>d1.prepare(s)));
}
globalThis.__auditEnv={DB:d1,RATE_LIMIT_SALT:'test-only',TELEGRAM_WEBHOOK_SECRET:'s'.repeat(24),TELEGRAM_CHAT_ID:'-100',WHATSAPP_VERIFY_TOKEN:'test',WHATSAPP_TOKEN:'test',WHATSAPP_PHONE_NUMBER_ID:'123',WHATSAPP_APP_SECRET:'test-secret',ANTHROPIC_API_KEY:'mock'};
globalThis.__translationCalls=0;
globalThis.fetch=async(url,init)=>{if(String(url).includes('anthropic.com')){globalThis.__translationCalls++;const body=JSON.parse(init.body);return new Response(JSON.stringify({id:'mock',type:'message',role:'assistant',model:'mock',stop_reason:'end_turn',content:[{type:'text',text:JSON.stringify(Object.fromEntries(Object.entries(JSON.parse(body.messages[0].content)).map(([k,v])=>[k,'TR:'+v])))}],usage:{input_tokens:1,output_tokens:1}}),{headers:{'content-type':'application/json'}});}throw new Error('External calls disabled in audit');};
const vite=await createServer({root,configFile:false,appType:'custom',resolve:{alias:{'@':root}},plugins:[{name:'audit-mocks',enforce:'pre',resolveId(id){if(id==='cloudflare:workers')return '\0audit-env';if(id==='@anthropic-ai/sdk')return '\0audit-model';},load(id){if(id==='\0audit-env')return 'export const env=globalThis.__auditEnv';if(id==='\0audit-model')return 'export default class Anthropic {messages={create:async (b)=>{globalThis.__translationCalls++;return {content:[{type:"text",text:JSON.stringify(Object.fromEntries(Object.entries(JSON.parse(b.messages[0].content)).map(([k,v])=>[k,"TR:"+v])))}],usage:{input_tokens:1,output_tokens:1}}}}}';}}],server:{middlewareMode:true,hmr:false}});
const {getDb}=await vite.ssrLoadModule('/db/index.ts'),schema=await vite.ssrLoadModule('/db/schema.ts'),db=getDb();
const admin=await vite.ssrLoadModule('/lib/customer-admin.ts'),auth=await vite.ssrLoadModule('/lib/customer-auth.ts');
const chat=await vite.ssrLoadModule('/lib/website-chat.ts'),telegram=await vite.ssrLoadModule('/app/api/integrations/telegram/webhook/route.ts');
const wa=await vite.ssrLoadModule('/app/api/integrations/whatsapp/webhook/route.ts');
const line=await vite.ssrLoadModule('/app/api/integrations/line/webhook/route.ts');
const tx=await vite.ssrLoadModule('/lib/site-translate.ts'),langs=await vite.ssrLoadModule('/lib/site-languages.ts');
const gps=await vite.ssrLoadModule('/lib/trip-live-data.ts');
const cp=await vite.ssrLoadModule('/lib/chat-pay.ts');
const now=new Date().toISOString(),later=new Date(Date.now()+86400000).toISOString();
try {
for(const id of ['alice','bob'])await db.insert(schema.customers).values({id,email:id+'@example.invalid',createdAt:now,updatedAt:now,lastSeenAt:now});
await db.insert(schema.bookings).values({reference:'ABCD23',customerName:'Alice private name',customerEmail:'alice@example.invalid',pickup:'Private hotel address',dropoff:'Bangkok',pickupDate:'2026-11-01',pickupTime:'09:00',passengers:2,luggage:1,vehicle:'economy_sedan',paymentMethod:'cash',total:2000,status:'confirmed',paymentStatus:'cash_due',accessTokenHash:'test',createdAt:now,updatedAt:now});
assert.equal((await admin.linkBookingToCustomer('bob','ABCD23',false,'test')).needsMove,true);
const moved=await admin.linkBookingToCustomer('bob','ABCD23',true,'test');
const [alice,bob]=await db.select().from(schema.customers);
const a=await auth.customerBooking(alice,'ABCD23'),b=await auth.customerBooking(bob,'ABCD23');
assert.ok(moved.ok&&!a&&b);
const counts=await admin.listCustomers('');assert.equal(counts.find(c=>c.id===alice.id).trips,0);assert.equal(counts.find(c=>c.id===bob.id).trips,1);console.log('Ownership requires confirmation and removes old email access');
await d1.prepare("INSERT INTO telegram_admins(telegram_user_id,display_name,enabled,created_at,updated_at) VALUES('777','Bob',1,?,?)").bind(now,now).run();
async function conv(id,extra={}){await db.insert(schema.websiteConversations).values({id,tokenHash:id,expiresAt:later,publicId:'WD-'+id,status:'open',createdAt:now,updatedAt:now,...extra});}
await conv('private',{assignedName:'Bob',assignedTelegramUserId:'777'});
await d1.prepare("INSERT INTO telegram_dm_messages(chat_id,message_id,conversation_id,created_at) VALUES('777',600,'private',?)").bind(now).run();
const request=(id,message)=>new Request('https://example.invalid/api/integrations/telegram/webhook',{method:'POST',headers:{'content-type':'application/json','x-telegram-bot-api-secret-token':'s'.repeat(24)},body:JSON.stringify({update_id:id,message})});
const pm={message_id:601,chat:{id:777,type:'private'},from:{id:777},text:'Private admin answer',reply_to_message:{message_id:600}};
await d1.prepare("CREATE TRIGGER fail_done BEFORE UPDATE ON telegram_events WHEN NEW.processing_status='done' BEGIN SELECT RAISE(FAIL,'simulated completion failure'); END").run();
assert.equal((await telegram.POST(request(6001,pm))).status,503);
await d1.prepare('DROP TRIGGER fail_done').run();assert.equal((await telegram.POST(request(6001,pm))).status,200);
assert.equal((await d1.prepare("SELECT COUNT(*) n FROM website_chat_messages WHERE conversation_id='private' AND sender='staff'").first()).n,1);
console.log('Telegram private retry produces one reply');
await conv('plain',{assignedName:'Bob',assignedTelegramUserId:'777'});
await d1.prepare("INSERT INTO telegram_reply_prompts(telegram_message_id,conversation_id,created_at,telegram_user_id) VALUES(700,'plain',?,'777')").bind(now).run();
await d1.prepare("CREATE TRIGGER fail_plain BEFORE INSERT ON website_chat_messages WHEN NEW.body='Plain answer' BEGIN SELECT RAISE(FAIL,'simulated save failure'); END").run();
const gm={message_id:701,chat:{id:-100,type:'group'},from:{id:777},text:'Plain answer'};
assert.equal((await telegram.POST(request(7001,gm))).status,503);await d1.prepare('DROP TRIGGER fail_plain').run();assert.equal((await telegram.POST(request(7001,gm))).status,200);
assert.equal((await d1.prepare("SELECT COUNT(*) n FROM website_chat_messages WHERE conversation_id='plain'").first()).n,1);console.log('Telegram plain reply survives a database failure');
await conv('staff-atomic',{assignedName:'Bob',assignedTelegramUserId:'777'});
await d1.prepare("CREATE TRIGGER fail_staff_update BEFORE UPDATE ON website_conversations WHEN NEW.id='staff-atomic' BEGIN SELECT RAISE(FAIL,'staff update failure'); END").run();
await assert.rejects(()=>chat.addStaffMessage('staff-atomic','Atomic reply',{name:'Bob',telegramUserId:'777'},'telegram',800,'777'));
assert.equal((await d1.prepare("SELECT COUNT(*) n FROM website_chat_messages WHERE conversation_id='staff-atomic'").first()).n,0);
await d1.prepare('DROP TRIGGER fail_staff_update').run();
await chat.addStaffMessage('staff-atomic','Atomic reply',{name:'Bob',telegramUserId:'777'},'telegram',800,'777');
await chat.addStaffMessage('staff-atomic','Other chat same message ID',{name:'Bob',telegramUserId:'777'},'telegram',800,'888');
assert.equal((await d1.prepare("SELECT COUNT(*) n FROM website_chat_messages WHERE conversation_id='staff-atomic'").first()).n,2);

await d1.prepare("CREATE TRIGGER fail_inbound BEFORE INSERT ON website_chat_messages WHEN NEW.sender='visitor' BEGIN SELECT RAISE(FAIL,'simulated incoming failure'); END").run();
const raw=JSON.stringify({entry:[{changes:[{value:{messages:[{from:'66800000000',id:'wa-audit',type:'text',text:{body:'Incoming customer message'}}]}}]}]});
const sig='sha256='+createHmac('sha256','test-secret').update(raw).digest('hex');
assert.equal((await wa.POST(new Request('https://example.invalid/whatsapp',{method:'POST',headers:{'x-hub-signature-256':sig},body:raw}))).status,503);await d1.prepare('DROP TRIGGER fail_inbound').run();
console.log('WhatsApp returns retryable failure');
delete globalThis.__auditEnv.ANTHROPIC_API_KEY;
const waRequest=()=>new Request('https://example.invalid/whatsapp',{method:'POST',headers:{'x-hub-signature-256':sig},body:raw});
assert.equal((await wa.POST(waRequest())).status,200);assert.equal((await wa.POST(waRequest())).status,200);
assert.equal((await d1.prepare("SELECT COUNT(*) n FROM website_chat_messages WHERE client_id='whatsapp:wa-audit'").first()).n,1);
globalThis.__auditEnv.LINE_CHANNEL_SECRET='line-secret';globalThis.__auditEnv.LINE_CHANNEL_ACCESS_TOKEN='line-token';
const lineRaw=JSON.stringify({events:[{type:'message',source:{type:'user',userId:'line-user'},message:{id:'line-audit',type:'text',text:'Line incoming'}}]});
const lineSig=createHmac('sha256','line-secret').update(lineRaw).digest('base64');
const lineRequest=()=>new Request('https://example.invalid/line',{method:'POST',headers:{'x-line-signature':lineSig},body:lineRaw});
await d1.prepare("CREATE TRIGGER fail_line BEFORE INSERT ON website_chat_messages WHEN NEW.client_id='line:line-audit' BEGIN SELECT RAISE(FAIL,'line insert failure'); END").run();
assert.equal((await line.POST(lineRequest())).status,503);await d1.prepare('DROP TRIGGER fail_line').run();
assert.equal((await line.POST(lineRequest())).status,200);assert.equal((await line.POST(lineRequest())).status,200);
assert.equal((await d1.prepare("SELECT COUNT(*) n FROM website_chat_messages WHERE client_id='line:line-audit'").first()).n,1);
globalThis.__auditEnv.ANTHROPIC_API_KEY='mock';

assert.equal(langs.untranslatedPath('/account/trips'),true);assert.equal(langs.untranslatedPath('/trip/ABCD23'),true);
const privateCalls=globalThis.__translationCalls;
await tx.translateMissing('ko',['Alice private name','Private hotel address'],'/trip/ABCD23');
await tx.translateMissing('ko',['Alice private name','Private hotel address'],'/');
assert.equal(globalThis.__translationCalls,privateCalls);
const saved=await d1.prepare("SELECT source,path FROM site_translations WHERE path='/trip/ABCD23'").all();assert.equal(saved.results.length,0);console.log('Private text never reaches the translation model or cache');
const calls=globalThis.__translationCalls;await Promise.all(Array.from({length:5},()=>tx.translateMissing('ko',['Book a ride'],'/')));assert.equal(globalThis.__translationCalls-calls,1);console.log('Concurrent translation requests share one model call');
assert.equal((await d1.prepare('SELECT COUNT(*) n FROM site_translation_claims').first()).n,0);
const expiredText='Free cancellation up to 48 hours';
await d1.prepare("INSERT INTO site_translation_claims(lang,hash,owner,expires_at) VALUES('ko',?,'dead-worker','2020-01-01T00:00:00.000Z')").bind(await tx.textHash(expiredText)).run();
assert.equal((await tx.translateMissing('ko',[expiredText],'/help')).get(expiredText),'TR:'+expiredText);

await db.insert(schema.drivers).values({id:'d',fullName:'Test Driver',phone:'0812345678',vehicle:'sedan',status:'active',createdAt:now,updatedAt:now});
for(const id of ['active','revoked'])await db.insert(schema.bookingAssignments).values({id,bookingReference:'ABCD23',leg:'outbound',driverId:'d',tokenHash:id,currentStatus:'trip_started',assignedBy:'test',assignedAt:now,tokenExpiresAt:later,revokedAt:id==='revoked'?now:null,updatedAt:now});
for(const [id,lat,at] of [['active',13.75,new Date(Date.now()-60000).toISOString()],['revoked',15.0,now]])await db.insert(schema.journeyLocations).values({id,bookingReference:'ABCD23',assignmentId:id,driverId:'d',latitude:lat,longitude:100.5,accuracyMetres:10,clientTimestamp:at,serverTimestamp:at,sequenceNumber:1,quality:'good',purgeAfter:later});
assert.equal((await gps.driverPosition('ABCD23')).lat,13.75);console.log('GPS uses only the active assignment');
await d1.prepare("UPDATE booking_assignments SET current_status='standby' WHERE id='active'").run();assert.equal((await gps.driverPosition('ABCD23')).lat,13.75);
await d1.prepare("UPDATE journey_locations SET quality='weak' WHERE assignment_id='active'").run();assert.equal(await gps.driverPosition('ABCD23'),null);
await d1.prepare("UPDATE journey_locations SET quality='good',server_timestamp='2020-01-01T00:00:00.000Z' WHERE assignment_id='active'").run();assert.equal(await gps.driverPosition('ABCD23'),null);

globalThis.__auditEnv.PAYSO_TEST_MODE='1';
await conv('paychat',{customerEmail:'pay@example.invalid'});
const linkId='a'.repeat(32);
await d1.prepare("INSERT INTO chat_payment_links(id,conversation_id,kind,details_json,vehicle,amount,customer_name,customer_phone,customer_email,status,created_at,expires_at) VALUES(?,?,'transfer',?,'economy_sedan',1000,'Pay Guest','0812345678','pay@example.invalid','pending',?,?)").bind(linkId,'paychat',JSON.stringify({pickup:'Bangkok',dropoff:'Pattaya',date:'2026-11-01',time:'09:00',passengers:2,bags:1,hours:null,summary:'Trip'}),now,later).run();
await d1.prepare("CREATE TRIGGER fail_paid BEFORE UPDATE ON chat_payment_links WHEN NEW.status='paid' BEGIN SELECT RAISE(FAIL,'simulated paid-link failure'); END").run();
await assert.rejects(()=>cp.markChatPaymentPaid(linkId,'test'));
assert.equal((await d1.prepare("SELECT COUNT(*) n FROM bookings WHERE customer_email='pay@example.invalid'").first()).n,0);
assert.equal((await cp.chatPaymentLink(linkId)).status,'pending');
await d1.prepare('DROP TRIGGER fail_paid').run();await cp.markChatPaymentPaid(linkId,'test');
assert.equal((await d1.prepare("SELECT COUNT(*) n FROM bookings WHERE customer_email='pay@example.invalid'").first()).n,1);
console.log('Failed payment transaction rolls back before retry');
const concurrentId='b'.repeat(32);
await d1.prepare("INSERT INTO chat_payment_links(id,conversation_id,kind,details_json,vehicle,amount,customer_name,customer_phone,customer_email,status,created_at,expires_at) SELECT ?,conversation_id,kind,details_json,vehicle,amount,customer_name,customer_phone,customer_email,'pending',created_at,expires_at FROM chat_payment_links WHERE id=?").bind(concurrentId,linkId).run();
const paidResults=await Promise.all(Array.from({length:5},()=>cp.markChatPaymentPaid(concurrentId,'test')));
assert.equal(paidResults.filter(r=>r.ok).length,1);assert.equal((await d1.prepare("SELECT COUNT(*) n FROM bookings WHERE customer_email='pay@example.invalid'").first()).n,2);

delete globalThis.__auditEnv.PAYSO_TEST_MODE;
globalThis.__auditEnv.PAYSO_MERCHANT_ID='configured';globalThis.__auditEnv.PAYSO_SECRET_KEY='configured';
assert.equal(cp.chatPaymentsEnabled(),false);assert.equal(await cp.paysoCheckoutUrl(await cp.chatPaymentLink(linkId)),null);
}finally{await vite.close();await mf.dispose();delete globalThis.__auditEnv;}
