"use client";
import { useCallback, useEffect, useState } from "react";
import { ictTime, type EvidencePolicy } from "@/lib/evidence-rules";
type Photo={id:string;event_type:string;leg:string;driver_name:string;assignment_id:string;received_at:string;device_captured_at:string;confirmed_at:string|null;latitude:number|null;longitude:number|null;accuracy_metres:number|null;expires_at:string;deleted_at:string|null};
type Data={evidence:Photo[];policy:EvidencePolicy;canSetPolicy:boolean;assignments:{id:string;leg:string;current_status:string}[];overrides:{assignment_id:string;event_type:string;reason:string;actor:string;created_at:string}[]};
const button="min-h-11 rounded-lg border px-4 py-2 font-semibold";
export function EvidenceAdmin({reference}:{reference:string}) {
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[chosen,setChosen]=useState(""),[type,setType]=useState("pickup"),[reason,setReason]=useState("");
 const load=useCallback(async()=>{const res=await fetch(`/api/admin/evidence?reference=${encodeURIComponent(reference)}`,{cache:"no-store"});const body=await res.json();if(!res.ok)throw new Error(body.error);setData(body);},[reference]);
 useEffect(()=>{const timer=setTimeout(()=>void load().catch(e=>setError(e.message)),0);return()=>clearTimeout(timer);},[load]);
 async function save(body:unknown){setBusy(true);setError("");try{const res=await fetch("/api/admin/evidence",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await res.json();if(!res.ok)throw new Error(result.error);await load();setReason("");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function policy(key:keyof EvidencePolicy,value:number){if(data)setData({...data,policy:{...data.policy,[key]:value}});}
 return <section className="mt-6 space-y-4 rounded-2xl border bg-white p-5"><div className="flex justify-between"><h2 className="text-xl font-bold">Trip photo evidence</h2><button type="button" className={button} onClick={()=>void load().catch(e=>setError(e.message))}>Refresh</button></div>
 <p className="text-sm text-slate-600">Private to operations and the assigned driver. GPS and device capture time are unverified. No customer photo access.</p>
 {error&&<p role="alert" className="text-red-700">{error}</p>}
 {data&&<><div className="grid gap-4 sm:grid-cols-2">{data.evidence.map(photo=><article key={photo.id} className="space-y-2 rounded-xl border p-3"><h3 className="font-bold">{photo.event_type.toUpperCase()} · {photo.leg} · {photo.driver_name}</h3><p className="break-all text-xs">Assignment: {photo.assignment_id}</p>{photo.deleted_at||photo.expires_at<=new Date().toISOString()?<p>Photo expired under retention policy.</p>:<><a href={`/api/admin/evidence/photos/${photo.id}`} target="_blank" rel="noreferrer"><img src={`/api/admin/evidence/photos/${photo.id}`} alt={`${photo.event_type} evidence`} className="max-h-96 w-full object-contain"/></a><a className="text-sm underline" href={`/api/admin/evidence/photos/${photo.id}?original=1`} target="_blank" rel="noreferrer">View EXIF-free original</a></>}
 <p className="text-sm">Device capture (unverified): {ictTime(photo.device_captured_at)}</p><p className="text-sm">Server received: {ictTime(photo.received_at)}</p><p className="text-sm font-semibold">{photo.confirmed_at?`Status confirmed: ${ictTime(photo.confirmed_at)}`:"Photo saved; no status confirmation attached"}</p><p className="text-sm">{photo.latitude===null?"Location unavailable":`${photo.latitude.toFixed(5)}, ${photo.longitude?.toFixed(5)} · ±${Math.round(photo.accuracy_metres??0)} m`}</p></article>)}</div>{data.evidence.length===0&&<p>No trip photos saved.</p>}
 <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Evidence policy and exceptions</summary>
 {data.canSetPolicy&&<div className="mt-4 space-y-3"><p className="text-sm">Global policy. Default: optional photos and GPS. Retention changes apply to new uploads.</p>{([['pickup_required','Require pickup photo at Waiting at pickup'],['dropoff_required','Require drop-off photo at Arrived'],['gps_required','Require acceptable GPS when confirming a photo']] as const).map(([key,label])=><label key={key} className="flex gap-2"><input type="checkbox" checked={Boolean(data.policy[key])} onChange={e=>policy(key,Number(e.target.checked))}/>{label}</label>)}
 {([['gps_timeout_ms','GPS timeout (milliseconds)',5000,60000],['max_accuracy_m','Maximum GPS uncertainty (metres)',10,2000],['retention_days','Photo retention (days)',1,90]] as const).map(([key,label,min,max])=><label key={key} className="flex flex-wrap items-center gap-2">{label}<input type="number" min={min} max={max} value={data.policy[key]} onChange={e=>policy(key,Number(e.target.value))} className="w-28 rounded border p-2"/></label>)}<button disabled={busy} type="button" className={button} onClick={()=>void save({action:"policy",policy:data.policy})}>Save policy</button></div>}
 <div className="mt-5 space-y-3"><h3 className="font-semibold">Authorize an evidence exception</h3><p className="text-sm">Waives photo/GPS requirements for one assignment and event. It does not advance the trip. The staff identity and reason are recorded.</p><select aria-label="Trip leg assignment" value={chosen} onChange={e=>setChosen(e.target.value)} className="w-full rounded border p-3"><option value="">Choose assignment</option>{data.assignments.map(a=><option key={a.id} value={a.id}>{a.leg} · {a.current_status} · {a.id}</option>)}</select><select aria-label="Evidence event" value={type} onChange={e=>setType(e.target.value)} className="rounded border p-3"><option value="pickup">Pickup</option><option value="dropoff">Drop-off</option></select><textarea aria-label="Exception reason" placeholder="Reason (at least 10 characters)" maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} className="w-full rounded border p-3"/><button type="button" disabled={busy||!chosen||reason.trim().length<10} className={button} onClick={()=>void save({assignmentId:chosen,eventType:type,reason})}>Record exception</button>{data.overrides.map(o=><p className="break-words text-sm" key={o.assignment_id+o.event_type}>{o.event_type} · {o.assignment_id}: {o.reason} · Staff {o.actor} · {ictTime(o.created_at)}</p>)}</div>
 </details></>}
 </section>;
}
