// Bangkok starter list for the place library. Imported as drafts: not verified and
// not shown on the website. Staff check hours, fees, map position, photos and
// wording, then press "Mark as verified" and publish. Coordinates are approximate.
import type { AttractionInput } from "@/lib/attractions";

type SeedProgram = { id: string; name: string; durationMin: number; arrivalBufferMin?: number; sessions: { time: string; days?: number[] }[] };
export type SeedPlace = Partial<Omit<AttractionInput, "programs">> & { programs?: SeedProgram[]; key: string; name: string; latitude: number; longitude: number; category: AttractionInput["category"]; durationMin: number };

const VERIFY = "Starter entry — check opening hours, entrance fees, exact pin, drop-off point and photos before publishing.";

export const BANGKOK_PLACES: SeedPlace[] = [
  // Temples and history (mornings are cooler and quieter; dress code applies)
  { key: "bkk-wat-arun", name: "Wat Arun (Temple of Dawn)", latitude: 13.7437, longitude: 100.4889, category: "temple", neighbourhood: "Thonburi riverside", openTime: "08:00", closeTime: "18:00", durationMin: 60, tags: ["temple", "photo"], bestTime: "morning", vibes: ["instagram"], dressCode: "Shoulders and knees covered", shortLine: "The riverside temple of porcelain-covered spires", description: "Wat Arun's tall prang is covered in coloured porcelain and seashells and rises over the Chao Phraya river. Climb the lower terraces for river views.", highlights: ["Porcelain-decorated central prang", "River views from the terraces", "Thai costume rental nearby for photos"] },
  { key: "bkk-wat-pho", name: "Wat Pho (Reclining Buddha)", latitude: 13.7465, longitude: 100.4927, category: "temple", neighbourhood: "Rattanakosin", openTime: "08:00", closeTime: "18:30", durationMin: 60, tags: ["temple", "photo"], bestTime: "morning", vibes: ["family"], dressCode: "Shoulders and knees covered", shortLine: "The 46-metre Reclining Buddha and Thai massage school", description: "Home of the gold-leafed Reclining Buddha and the traditional school of Thai massage, with quiet courtyards full of chedis.", highlights: ["Reclining Buddha", "Hundreds of chedis and Buddha images", "Traditional Thai massage on site"] },
  { key: "bkk-grand-palace", name: "Grand Palace and Wat Phra Kaew", latitude: 13.75, longitude: 100.4913, category: "temple", neighbourhood: "Rattanakosin", openTime: "08:30", closeTime: "15:30", lastEntry: "15:30", durationMin: 120, tags: ["palace", "temple", "photo"], bestTime: "morning", vibes: ["instagram"], dressCode: "Long trousers or skirt, covered shoulders, no see-through clothing", shortLine: "Thailand's royal palace and the Emerald Buddha", description: "The former royal residence and the Temple of the Emerald Buddha. The busiest sight in Bangkok, so arrive early. It can close for royal ceremonies.", highlights: ["Temple of the Emerald Buddha", "Royal throne halls", "Murals of the Ramakien"] },
  { key: "bkk-golden-mount", name: "Wat Saket (Golden Mount)", latitude: 13.7539, longitude: 100.5066, category: "temple", neighbourhood: "Old Town", openTime: "07:00", closeTime: "19:00", durationMin: 45, tags: ["temple", "photo", "outdoor"], bestTime: "sunset", shortLine: "Climb 300 steps for a view over old Bangkok", description: "A golden chedi on a man-made hill. The spiral walk to the top passes bells and gongs and ends with a 360° view of the old city.", highlights: ["Panoramic old-town view", "Bells along the stairway"] },
  { key: "bkk-marble-temple", name: "Wat Benchamabophit (Marble Temple)", latitude: 13.7663, longitude: 100.5143, category: "temple", neighbourhood: "Dusit", openTime: "08:00", closeTime: "18:00", durationMin: 40, tags: ["temple", "photo"], bestTime: "morning", dressCode: "Shoulders and knees covered", shortLine: "Italian marble and a gallery of 50 Buddha images", description: "An elegant temple built of white Carrara marble, with a courtyard gallery of Buddha images in many styles.", highlights: ["White marble ordination hall", "Buddha image gallery"] },
  { key: "bkk-wat-traimit", name: "Wat Traimit (Golden Buddha)", latitude: 13.7378, longitude: 100.5136, category: "temple", neighbourhood: "Chinatown", openTime: "08:00", closeTime: "17:00", durationMin: 40, tags: ["temple"], bestTime: "morning", dressCode: "Shoulders and knees covered", shortLine: "A five-tonne solid gold Buddha at the gate of Chinatown", description: "The world's largest solid-gold seated Buddha, rediscovered under plaster in the 1950s, with a small museum about Chinatown.", highlights: ["Golden Buddha", "Yaowarat heritage exhibition"] },
  { key: "bkk-wat-paknam", name: "Wat Paknam Phasi Charoen", latitude: 13.7218, longitude: 100.4699, category: "temple", neighbourhood: "Phasi Charoen", openTime: "08:00", closeTime: "18:00", durationMin: 60, tags: ["temple", "photo"], vibes: ["instagram"], dressCode: "Shoulders and knees covered", shortLine: "A giant Buddha and the famous glass-stupa ceiling", description: "A canal-side temple with a 69-metre seated Buddha and a white stupa whose top floor holds a jade-green glass stupa under a painted ceiling.", highlights: ["Glass stupa and painted ceiling", "Giant seated Buddha"] },
  { key: "bkk-loha-prasat", name: "Wat Ratchanatdaram (Loha Prasat)", latitude: 13.7546, longitude: 100.504, category: "temple", neighbourhood: "Old Town", durationMin: 40, tags: ["temple", "photo"], shortLine: "The metal castle with 37 iron spires", description: "A rare multi-tiered 'metal castle' with 37 spires; walk up through the corridors for views of the Golden Mount.", highlights: ["37 metal spires", "Views to the Golden Mount"] },
  { key: "bkk-jim-thompson", name: "Jim Thompson House", latitude: 13.7492, longitude: 100.5283, category: "museum", neighbourhood: "Siam", openTime: "10:00", closeTime: "18:00", durationMin: 75, tags: ["photo"], vibes: ["rainy-day"], shortLine: "Teak houses and the story of Thai silk", description: "Six traditional teak houses filled with Asian art, built by the American who revived the Thai silk industry. Visits are by guided tour.", highlights: ["Guided house tour", "Tropical garden", "Silk shop and café"] },
  { key: "bkk-national-museum", name: "Bangkok National Museum", latitude: 13.7577, longitude: 100.492, category: "museum", neighbourhood: "Rattanakosin", openTime: "09:00", closeTime: "16:00", closedDays: [1, 2], durationMin: 90, vibes: ["rainy-day"], shortLine: "Thai art and history in a former palace", description: "Thailand's largest museum, in the former Front Palace, covering Thai art and history from prehistory to today.", highlights: ["Buddhaisawan Chapel murals", "Royal funeral chariots"] },
  { key: "bkk-erawan-shrine", name: "Erawan Shrine", latitude: 13.7445, longitude: 100.5404, category: "sight", neighbourhood: "Ratchaprasong", durationMin: 20, tags: ["photo"], shortLine: "Bangkok's busiest shrine, with live Thai dancers", description: "A small Hindu shrine to Brahma at a busy crossroads, where worshippers hire traditional dancers to give thanks.", highlights: ["Traditional dance offerings"] },

  // Viewpoints and rooftops
  { key: "bkk-mahanakhon", name: "King Power Mahanakhon SkyWalk", latitude: 13.7234, longitude: 100.5285, category: "viewpoint", neighbourhood: "Silom", openTime: "10:00", closeTime: "23:59", durationMin: 75, tags: ["photo"], bestTime: "sunset", vibes: ["instagram", "family", "rainy-day"], shortLine: "Walk on glass 314 metres above Bangkok", description: "Thailand's highest observation deck with an open-air rooftop and a glass floor over the city. Sunset slots are the most popular.", highlights: ["Glass Tray floor", "360° rooftop view", "Sunset over the river"], reservationNote: "Sunset time slots sell out; book ahead." },
  { key: "bkk-baiyoke-sky", name: "Baiyoke Sky Observation Deck", latitude: 13.7543, longitude: 100.5404, category: "viewpoint", neighbourhood: "Pratunam", durationMin: 60, tags: ["photo"], bestTime: "night", vibes: ["family", "budget"], shortLine: "A revolving roof deck over Pratunam", description: "A revolving open-air deck near the top of Baiyoke Tower II, with buffet restaurants below.", highlights: ["Revolving roof deck"] },
  { key: "bkk-sky-bar", name: "Sky Bar at Lebua", latitude: 13.7215, longitude: 100.5168, category: "rooftop", neighbourhood: "Bang Rak", openTime: "18:00", closeTime: "23:59", durationMin: 60, tags: ["night", "photo"], bestTime: "night", vibes: ["romantic", "luxury"], dressCode: "Smart casual; no shorts, sleeveless shirts or flip-flops", mealSlots: ["night"], priceLevel: 4, shortLine: "The golden-dome rooftop bar over the river", description: "An open-air bar on the 63rd floor beneath the gold dome of State Tower, with river and skyline views." },
  { key: "bkk-octave", name: "Octave Rooftop Bar (Marriott Sukhumvit)", latitude: 13.7259, longitude: 100.5808, category: "rooftop", neighbourhood: "Thonglor", openTime: "17:00", closeTime: "23:59", durationMin: 60, tags: ["night"], bestTime: "sunset", vibes: ["romantic"], mealSlots: ["night"], priceLevel: 3, shortLine: "Three levels of 360° views in Thonglor", description: "A three-level rooftop bar with a circular top deck and views across Sukhumvit." },
  { key: "bkk-vertigo", name: "Vertigo at Banyan Tree", latitude: 13.7239, longitude: 100.5398, category: "rooftop", neighbourhood: "Sathorn", durationMin: 90, tags: ["night"], bestTime: "night", vibes: ["romantic", "luxury"], mealSlots: ["dinner", "night"], priceLevel: 4, shortLine: "Open-air rooftop dining on the 61st floor", description: "A rooftop grill and bar with an open edge over Sathorn; dinner reservations recommended.", reservationNote: "Reserve ahead; closes in heavy rain." },

  // Cafés (breakfast, brunch, afternoon)
  { key: "bkk-vivi-coffee", name: "Vivi The Coffee Place", latitude: 13.7453, longitude: 100.4908, category: "cafe", neighbourhood: "Tha Tien riverside", durationMin: 45, mealSlots: ["breakfast", "brunch", "afternoon"], priceLevel: 2, vibes: ["instagram"], bestTime: "morning", shortLine: "Riverside coffee facing Wat Arun", description: "A small riverside café with a deck looking straight across to Wat Arun." },
  { key: "bkk-blue-whale", name: "Blue Whale Café", latitude: 13.7451, longitude: 100.4925, category: "cafe", neighbourhood: "Tha Tien", durationMin: 40, mealSlots: ["breakfast", "brunch", "afternoon"], priceLevel: 2, vibes: ["instagram"], shortLine: "The blue butterfly-pea latte near Wat Pho", description: "A cosy café a short walk from Wat Pho, known for its blue butterfly-pea drinks." },
  { key: "bkk-kopi-hya-tai-kee", name: "Kope Hya Tai Kee", latitude: 13.7532, longitude: 100.4983, category: "cafe", neighbourhood: "Old Town", durationMin: 40, mealSlots: ["breakfast"], priceLevel: 1, vibes: ["local-favourite", "budget"], bestTime: "morning", shortLine: "A Hainanese coffee shop serving breakfast since 1952", description: "An old-school coffee shop on Phraeng Phuthon square: eggs in a pan, toast and strong Thai coffee." },
  { key: "bkk-on-lok-yun", name: "On Lok Yun", latitude: 13.7449, longitude: 100.4999, category: "cafe", neighbourhood: "Charoen Krung", durationMin: 40, mealSlots: ["breakfast"], priceLevel: 1, vibes: ["local-favourite", "budget"], bestTime: "morning", shortLine: "A vintage breakfast diner from the 1930s", description: "A family-run diner near Sala Chalermkrung serving Thai-style breakfasts in a vintage room." },
  { key: "bkk-gallery-drip", name: "Gallery Drip Coffee (BACC)", latitude: 13.7466, longitude: 100.5302, category: "cafe", neighbourhood: "Siam", durationMin: 40, mealSlots: ["brunch", "afternoon"], priceLevel: 2, vibes: ["rainy-day"], shortLine: "Hand-drip coffee inside the Bangkok Art and Culture Centre", description: "A pour-over coffee bar on the ground floor of the BACC art centre, ideal with an exhibition visit." },
  { key: "bkk-roast", name: "Roast (EmQuartier)", latitude: 13.7316, longitude: 100.5698, category: "cafe", neighbourhood: "Phrom Phong", durationMin: 60, mealSlots: ["breakfast", "brunch"], priceLevel: 3, vibes: ["family"], shortLine: "All-day brunch and coffee in Phrom Phong", description: "A popular all-day brunch restaurant and coffee roaster in the EmQuartier mall." },
  { key: "bkk-rocket-sathorn", name: "Rocket Coffeebar Sathorn", latitude: 13.7219, longitude: 100.5299, category: "cafe", neighbourhood: "Sathorn", durationMin: 45, mealSlots: ["breakfast", "brunch"], priceLevel: 3, shortLine: "Scandinavian-style breakfast and coffee", description: "A bright Nordic-style café known for breakfast plates and good coffee." },
  { key: "bkk-landhaus-ari", name: "Landhaus Bakery Ari", latitude: 13.7798, longitude: 100.5432, category: "cafe", neighbourhood: "Ari", durationMin: 45, mealSlots: ["breakfast", "brunch"], priceLevel: 2, vibes: ["local-favourite"], shortLine: "Japanese-style bakery in leafy Ari", description: "A bakery café in the Ari neighbourhood known for breads and pastries." },

  // Restaurants
  { key: "bkk-thipsamai", name: "Thipsamai Pad Thai", latitude: 13.7529, longitude: 100.505, category: "restaurant", neighbourhood: "Old Town", durationMin: 50, mealSlots: ["lunch", "dinner"], priceLevel: 2, vibes: ["local-favourite"], shortLine: "Bangkok's most famous pad thai, wrapped in egg", description: "A long-running pad thai shop near the Golden Mount; expect a queue at peak times.", reservationNote: "Queues at lunch and evening peaks." },
  { key: "bkk-jay-fai", name: "Jay Fai", latitude: 13.7525, longitude: 100.5049, category: "restaurant", neighbourhood: "Old Town", durationMin: 90, mealSlots: ["lunch", "dinner"], priceLevel: 4, vibes: ["local-favourite"], shortLine: "Michelin-starred street-food crab omelette", description: "A Michelin-starred street-food stall famous for crab omelette and drunken noodles, cooked over charcoal by Jay Fai herself.", reservationNote: "Very long waits; reservations are hard to get. Check opening days." },
  { key: "bkk-krua-apsorn", name: "Krua Apsorn (Dinso)", latitude: 13.7558, longitude: 100.5014, category: "restaurant", neighbourhood: "Old Town", durationMin: 60, mealSlots: ["lunch"], priceLevel: 2, vibes: ["local-favourite", "family"], shortLine: "Classic Thai home cooking with a famous crab curry", description: "A well-loved Thai restaurant known for its crab meat in yellow curry and crab omelette." },
  { key: "bkk-supanniga-riverside", name: "Supanniga Eating Room (Tha Tien)", latitude: 13.7445, longitude: 100.4906, category: "restaurant", neighbourhood: "Tha Tien riverside", durationMin: 75, mealSlots: ["lunch", "dinner"], priceLevel: 3, vibes: ["romantic"], shortLine: "Eastern-Thai recipes with a Wat Arun view", description: "Family recipes from Trat and Isan on a riverside terrace facing Wat Arun.", reservationNote: "Book the terrace for sunset." },
  { key: "bkk-sala-rattanakosin", name: "Sala Rattanakosin", latitude: 13.7448, longitude: 100.4904, category: "restaurant", neighbourhood: "Tha Tien riverside", durationMin: 75, mealSlots: ["lunch", "dinner", "night"], priceLevel: 3, vibes: ["romantic"], shortLine: "Rooftop dining facing Wat Arun", description: "A boutique hotel restaurant and rooftop bar directly across the river from Wat Arun." },
  { key: "bkk-somtum-der", name: "Somtum Der (Sala Daeng)", latitude: 13.7278, longitude: 100.5355, category: "restaurant", neighbourhood: "Silom", durationMin: 60, mealSlots: ["lunch", "dinner"], priceLevel: 2, vibes: ["local-favourite"], shortLine: "Isan papaya salads and grilled chicken", description: "A lively northeastern Thai restaurant near Lumpini Park." },
  { key: "bkk-nai-mong-hoi-tod", name: "Nai Mong Hoi Tod", latitude: 13.7417, longitude: 100.5103, category: "restaurant", neighbourhood: "Chinatown", durationMin: 40, mealSlots: ["lunch", "dinner"], priceLevel: 1, vibes: ["local-favourite", "budget"], shortLine: "Crispy oyster omelette in Chinatown", description: "A small Chinatown shop famous for its crispy oyster and mussel omelettes." },
  { key: "bkk-kuang-heng", name: "Go-Ang Kaomunkai Pratunam", latitude: 13.7503, longitude: 100.5418, category: "restaurant", neighbourhood: "Pratunam", durationMin: 40, mealSlots: ["breakfast", "lunch", "dinner"], priceLevel: 1, vibes: ["local-favourite", "budget"], shortLine: "The famous pink-shirt chicken rice", description: "A famous Hainanese chicken rice shop in Pratunam, quick and inexpensive." },
  { key: "bkk-baan-khanitha", name: "Baan Khanitha (Sukhumvit 23)", latitude: 13.7389, longitude: 100.5627, category: "restaurant", neighbourhood: "Asok", durationMin: 75, mealSlots: ["lunch", "dinner"], priceLevel: 3, vibes: ["family", "romantic"], shortLine: "Elegant Thai dining in a garden house", description: "Classic Thai dishes served in a converted house with a garden." },
  { key: "bkk-yaowarat-food", name: "Yaowarat Road street food", latitude: 13.74, longitude: 100.51, category: "market", neighbourhood: "Chinatown", openTime: "17:00", closeTime: "23:59", durationMin: 90, tags: ["night", "market"], mealSlots: ["dinner", "night"], priceLevel: 1, bestTime: "night", vibes: ["local-favourite", "instagram"], shortLine: "Chinatown's neon street-food strip", description: "After dark Yaowarat Road fills with stalls selling seafood, noodles, dumplings and desserts under neon signs.", dropoffNote: "Cars can't stop on Yaowarat Road at night; drop at the end of a side street." },

  // Hidden gems
  { key: "bkk-talat-noi", name: "Talat Noi", latitude: 13.733, longitude: 100.5137, category: "hidden-gem", neighbourhood: "Talat Noi", durationMin: 75, tags: ["photo", "outdoor"], vibes: ["instagram", "local-favourite"], bestTime: "morning", shortLine: "Street art, old shophouses and river lanes", description: "A historic riverside quarter of narrow lanes, car-part workshops, street art and old Chinese houses.", highlights: ["Street art", "Riverside lanes", "Old Chinese shophouses"] },
  { key: "bkk-so-heng-tai", name: "So Heng Tai Mansion", latitude: 13.7325, longitude: 100.5131, category: "hidden-gem", neighbourhood: "Talat Noi", durationMin: 30, tags: ["photo"], shortLine: "A 200-year-old Chinese courtyard house", description: "A private Hokkien-style mansion in Talat Noi with a courtyard pool; check visiting hours." },
  { key: "bkk-bang-luang-artist-house", name: "Khlong Bang Luang Artist House", latitude: 13.7356, longitude: 100.472, category: "hidden-gem", neighbourhood: "Thonburi", durationMin: 75, tags: ["photo"], vibes: ["family", "local-favourite"], shortLine: "A canal-side art house with a traditional puppet show", description: "A wooden house on the Thonburi canals with art, a small café and a traditional Thai puppet show at a set time.", programs: [{ id: "puppet-show", name: "Thai puppet show", durationMin: 45, arrivalBufferMin: 10, sessions: [{ time: "14:00", days: [0, 1, 2, 4, 5, 6] }] }], internalNotes: `${VERIFY} Confirm the puppet show time and the weekday it is off.` },
  { key: "bkk-bang-krachao", name: "Bang Krachao (Green Lung)", latitude: 13.693, longitude: 100.566, category: "nature", neighbourhood: "Bang Krachao", durationMin: 150, tags: ["nature", "outdoor", "hiking"], vibes: ["family"], bestTime: "morning", shortLine: "Cycle through jungle paths minutes from the city", description: "A green island in a bend of the river with raised cycling paths, gardens and a weekend floating market.", highlights: ["Bike rental and raised paths", "Sri Nakhon Khuean Khan Park"] },
  { key: "bkk-song-wat", name: "Song Wat Road", latitude: 13.7385, longitude: 100.5085, category: "hidden-gem", neighbourhood: "Chinatown", durationMin: 60, tags: ["photo", "outdoor"], vibes: ["instagram"], shortLine: "Chinatown's old trading street, now full of cafés", description: "An old riverside trading street of warehouses and spice shops, now mixed with cafés, galleries and murals." },
  { key: "bkk-nang-loeng", name: "Nang Loeng Market", latitude: 13.76, longitude: 100.511, category: "market", neighbourhood: "Dusit", durationMin: 45, tags: ["market"], mealSlots: ["lunch"], vibes: ["local-favourite", "budget"], bestTime: "midday", shortLine: "A 120-year-old market for Thai desserts", description: "One of Bangkok's oldest markets, known for traditional sweets and lunchtime curries." },
  { key: "bkk-kudi-chin", name: "Kudi Chin community", latitude: 13.74, longitude: 100.4925, category: "hidden-gem", neighbourhood: "Thonburi riverside", durationMin: 60, tags: ["photo"], shortLine: "Portuguese-Thai heritage and Santa Cruz church", description: "A riverside community founded by Portuguese settlers, with Santa Cruz church and Portuguese-Thai cakes." },
  { key: "bkk-pak-khlong-talat", name: "Pak Khlong Talat (Flower Market)", latitude: 13.743, longitude: 100.497, category: "market", neighbourhood: "Rattanakosin", durationMin: 40, tags: ["market", "photo"], bestTime: "morning", vibes: ["instagram", "local-favourite"], shortLine: "Bangkok's 24-hour flower market", description: "Mountains of marigolds, orchids and jasmine garlands; most colourful early in the morning or late at night." },
  { key: "bkk-lhong-1919", name: "Lhong 1919", latitude: 13.7344, longitude: 100.5108, category: "hidden-gem", neighbourhood: "Khlong San", durationMin: 60, tags: ["photo"], vibes: ["instagram"], shortLine: "A restored Chinese pier house with murals", description: "A 19th-century Chinese trading house on the river, restored with a shrine, murals, shops and cafés." },
  { key: "bkk-phra-sumen", name: "Phra Sumen Fort and Santichaiprakarn Park", latitude: 13.7637, longitude: 100.4956, category: "sight", neighbourhood: "Banglamphu", durationMin: 30, tags: ["outdoor", "photo"], bestTime: "sunset", vibes: ["budget"], shortLine: "A riverside fort and sunset park near Khao San", description: "One of the last city forts, with a small riverside park popular at sunset." },
  { key: "bkk-chang-chui", name: "Chang Chui Creative Park", latitude: 13.786, longitude: 100.479, category: "hidden-gem", neighbourhood: "Bang Phlat", durationMin: 75, tags: ["night", "photo"], bestTime: "night", vibes: ["instagram"], shortLine: "An art market around a real airliner", description: "A creative night market built around a retired airliner, with art, bars and food stalls." },

  // Markets and shopping
  { key: "bkk-chatuchak", name: "Chatuchak Weekend Market", latitude: 13.7999, longitude: 100.5503, category: "market", neighbourhood: "Chatuchak", openTime: "09:00", closeTime: "18:00", closedDays: [1, 2, 3, 4, 5], durationMin: 150, tags: ["market", "outdoor"], vibes: ["budget", "family"], bestTime: "morning", shortLine: "15,000 stalls, weekends only", description: "One of the world's largest weekend markets: clothes, crafts, plants, antiques and street food.", internalNotes: `${VERIFY} Weekend-only; some sections open on Friday evening.` },
  { key: "bkk-or-tor-kor", name: "Or Tor Kor Market", latitude: 13.8, longitude: 100.548, category: "market", neighbourhood: "Chatuchak", durationMin: 45, tags: ["market"], mealSlots: ["breakfast", "lunch"], vibes: ["local-favourite"], shortLine: "Bangkok's cleanest fresh market and Thai fruit", description: "A premium fresh market next to Chatuchak with the best Thai fruit, curries and ready-made food." },
  { key: "bkk-jodd-fairs", name: "Jodd Fairs Rama 9", latitude: 13.7573, longitude: 100.5657, category: "market", neighbourhood: "Rama 9", openTime: "16:00", closeTime: "23:59", durationMin: 90, tags: ["night", "market"], mealSlots: ["dinner", "night"], vibes: ["instagram", "budget"], bestTime: "night", shortLine: "The night market with the famous volcano ribs", description: "A popular night market of food stalls, bars and small shops." },
  { key: "bkk-asiatique", name: "Asiatique The Riverfront", latitude: 13.7046, longitude: 100.503, category: "shopping", neighbourhood: "Charoen Krung", openTime: "16:00", closeTime: "23:59", durationMin: 120, tags: ["night"], mealSlots: ["dinner"], vibes: ["family", "romantic"], bestTime: "night", shortLine: "Riverside night bazaar with a big wheel", description: "An open-air riverside mall in old warehouses, with a Ferris wheel, restaurants and shows." },
  { key: "bkk-iconsiam", name: "ICONSIAM", latitude: 13.7266, longitude: 100.5106, category: "shopping", neighbourhood: "Khlong San", openTime: "10:00", closeTime: "22:00", durationMin: 120, mealSlots: ["lunch", "dinner"], vibes: ["family", "rainy-day"], shortLine: "Riverside mall with an indoor floating market", description: "A riverside shopping mall whose ground floor, SookSiam, recreates a floating market with food from around Thailand." },
  { key: "bkk-damnoen-saduak", name: "Damnoen Saduak Floating Market", latitude: 13.5197, longitude: 99.959, category: "market", neighbourhood: "Ratchaburi (day trip)", openTime: "07:00", closeTime: "12:00", durationMin: 120, tags: ["market", "boat", "photo"], vibes: ["instagram", "family"], bestTime: "morning", shortLine: "The classic floating market, best before 10:00", description: "Vendors in wooden boats sell fruit, noodles and souvenirs along the canals. About 1.5–2 hours from Bangkok; go early." },
  { key: "bkk-maeklong-railway", name: "Maeklong Railway Market", latitude: 13.4074, longitude: 100.0003, category: "market", neighbourhood: "Samut Songkhram (day trip)", durationMin: 60, tags: ["market", "photo"], vibes: ["instagram"], shortLine: "The market that folds away when the train passes", description: "Stalls sit on the railway tracks and pull back their awnings moments before the train rolls through.", programs: [{ id: "train", name: "Train passing", durationMin: 30, arrivalBufferMin: 20, sessions: [] }], internalNotes: `${VERIFY} Add the current train times as sessions so trips are planned around them.` },

  // Activities, shows and parks
  { key: "bkk-river-cruise", name: "Chao Phraya dinner cruise", latitude: 13.727, longitude: 100.51, category: "activity", neighbourhood: "Riverside", durationMin: 120, tags: ["boat", "night"], mealSlots: ["dinner"], vibes: ["romantic", "family"], bestTime: "night", shortLine: "Dinner on the river past lit-up temples", description: "An evening cruise past Wat Arun and the Grand Palace with a buffet dinner.", internalNotes: `${VERIFY} Add the operator as a supplier and the boarding time as a session.` },
  { key: "bkk-rajadamnern", name: "Rajadamnern Muay Thai Stadium", latitude: 13.7593, longitude: 100.51, category: "show", neighbourhood: "Banglamphu", durationMin: 150, tags: ["night"], bestTime: "night", shortLine: "Live Muay Thai at the oldest stadium", description: "Thailand's oldest boxing stadium, with fight nights through the week.", internalNotes: `${VERIFY} Add fight nights and start times as sessions.` },
  { key: "bkk-sea-life", name: "SEA LIFE Bangkok Ocean World", latitude: 13.7462, longitude: 100.5348, category: "animal", neighbourhood: "Siam", openTime: "10:00", closeTime: "20:00", durationMin: 120, tags: ["animal"], vibes: ["family", "rainy-day"], shortLine: "A big aquarium under Siam Paragon", description: "A large aquarium with a shark tunnel and penguins, in the basement of Siam Paragon." },
  { key: "bkk-lumpini", name: "Lumpini Park", latitude: 13.7314, longitude: 100.5414, category: "nature", neighbourhood: "Silom", openTime: "04:30", closeTime: "21:00", durationMin: 45, tags: ["nature", "outdoor"], vibes: ["family", "budget"], bestTime: "morning", shortLine: "Bangkok's central park, with monitor lizards", description: "A large green park with a lake, paddle boats, joggers and wild monitor lizards." },
  { key: "bkk-benjakitti", name: "Benjakitti Forest Park", latitude: 13.73, longitude: 100.558, category: "nature", neighbourhood: "Khlong Toei", durationMin: 60, tags: ["nature", "outdoor"], vibes: ["family", "budget", "instagram"], bestTime: "morning", shortLine: "Elevated walkways through a city wetland", description: "A newer forest park with elevated skywalks over wetlands and views of the skyline." },
];

/** Converts a seed entry into the shape the attraction editor saves. */
export function seedToInput(p: SeedPlace): AttractionInput {
  return {
    name: p.name, customerName: null, area: "Bangkok", address: null, latitude: p.latitude, longitude: p.longitude, googlePlaceId: null, category: p.category,
    tags: p.tags ?? [], openTime: p.openTime ?? null, closeTime: p.closeTime ?? null, lastEntry: p.lastEntry ?? null, closedDays: p.closedDays ?? [],
    durationMin: p.durationMin, arrivalBufferMin: p.arrivalBufferMin ?? 0, bookingRequired: p.bookingRequired ?? false, weatherSensitive: p.weatherSensitive ?? false,
    dressCode: p.dressCode ?? null, description: p.description ?? null, highlights: p.highlights ?? [], bring: p.bring ?? [], coverImage: null, gallery: [],
    imageCredit: null, website: null, phone: null, internalNotes: p.internalNotes ?? VERIFY, supplierId: null,
    programs: (p.programs ?? []).map((x) => ({ feeAdult: 0, feeChild: 0, feeIncluded: false, bookingRequired: false, arrivalBufferMin: 0, ...x })),
    exceptions: [], status: "active", mealSlots: p.mealSlots ?? [], priceLevel: p.priceLevel ?? null, avgSpend: p.avgSpend ?? null,
    neighbourhood: p.neighbourhood ?? null, bestTime: p.bestTime ?? null, vibes: p.vibes ?? [], dropoffNote: p.dropoffNote ?? null,
    reservationNote: p.reservationNote ?? null, shortLine: p.shortLine ?? null, published: false, i18n: {},
  };
}
