"use client";
import { useEffect, useState, useCallback, type FormEvent } from "react";
type Conversation={id:string;preview:string;updated_at:string};type Message={sender:string;body:string;created_at:string};
export default function ChatInbox(){const [conversations,setConversations]=useState<Conversation[]>([]),[id,setId]=useState(""),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{const r=await fetch(`/api/admin/chat${id?`?id=${encodeURIComponent(id)}`:""}`,{cache:"no-store"});const data=await r.json();if(!r.ok){setError(data.error);return;}if(id)setMessages(data.messages);else setConversations(data.conversations);},[id]);
 useEffect(()=>{const first=setTimeout(()=>void load(),0);const timer=setInterval(()=>void load(),10000);return()=>{clearTimeout(first);clearInterval(timer);};},[load]);
 async function send(e:FormEvent){e.preventDefault();const r=await fetch("/api/admin/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,message:text})});const data=await r.json();if(!r.ok)setError(data.error);else{setText("");await load();}}
 return <main className="mx-auto max-w-3xl space-y-4 p-8"><h1 className="text-3xl font-bold">Website chat</h1><p role="alert">{error}</p>{id?<><button className="underline" onClick={()=>setId("")}>All conversations</button>{messages.map((m,i)=><div key={i} className="rounded border p-3"><strong>{m.sender}</strong><p className="whitespace-pre-wrap break-words">{m.body}</p></div>)}<form onSubmit={send} className="grid gap-3"><textarea aria-label="Reply" required maxLength={2000} className="rounded border p-3" value={text} onChange={e=>setText(e.target.value)}/><button className="rounded bg-orange-500 p-3">Send reply</button></form></>:conversations.map(c=><button key={c.id} className="block w-full rounded border p-4 text-left" onClick={()=>setId(c.id)}>{c.preview}<small className="block">{c.updated_at}</small></button>)}</main>;
}
