import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, Clock3, MapPin, Route } from "lucide-react";
import { PublicFooter } from "@/components/public-footer";
import { destinations, SITE_URL } from "@/lib/public-content";

export function generateStaticParams(){return destinations.map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const d=destinations.find(x=>x.slug===slug);if(!d)return{};return{title:`Private transfers in ${d.name} | Waydidi`,description:d.intro,alternates:{canonical:`${SITE_URL}/destinations/${d.slug}`},openGraph:{title:`Private transfers in ${d.name} | Waydidi`,description:d.intro,url:`${SITE_URL}/destinations/${d.slug}`,type:"website"}}}
export default async function DestinationPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const d=destinations.find(x=>x.slug===slug);if(!d)notFound();return <main className="bg-white text-[#211726]">
  <section className="mx-auto max-w-[1280px] px-5 pt-5 lg:px-8"><div className="relative overflow-hidden rounded-[30px] px-6 py-14 text-white sm:px-10 lg:px-16 lg:py-20" style={{backgroundColor:d.color}}><div className="absolute -right-20 top-0 h-full w-[44%] rotate-[-8deg] bg-[#FF8A05] opacity-85"/><div className="relative max-w-3xl"><a href="/destinations" className="inline-flex items-center gap-2 text-sm font-bold text-white/70"><ArrowLeft size={16}/> All destinations</a><p className="mt-12 text-sm font-black uppercase tracking-[.18em] text-[#FFB25A]">{d.kicker}</p><h1 className="mt-3 text-5xl font-black tracking-[-.05em] sm:text-7xl">Private transfers in {d.name}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/80">{d.intro}</p><a href="/#booking-search" className="mt-9 inline-flex items-center gap-2 rounded-full bg-white px-6 py-4 font-black text-[#C96100]">Book a {d.name} ride <ArrowRight size={18}/></a></div></div></section>
  <section className="mx-auto grid max-w-[1180px] gap-8 px-5 py-16 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-sm font-black uppercase tracking-[.18em] text-[#D96F00]">Where Waydidi helps</p><h2 className="mt-2 text-3xl font-black tracking-[-.035em] sm:text-5xl">Arrive with the next step already arranged.</h2><div className="mt-8 grid gap-3">{d.highlights.map(h=><div key={h} className="flex items-start gap-4 rounded-2xl bg-[#F5F6F8] p-5"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[#FFF0DF] text-[#D96F00]"><Check size={18}/></span><span className="pt-1 font-bold">{h}</span></div>)}</div></div><aside className="rounded-[26px] bg-[#FFF0DF] p-6 sm:p-8"><Clock3 className="text-[#D96F00]"/><h2 className="mt-5 text-2xl font-black">Local travel note</h2><p className="mt-3 text-lg leading-8 text-slate-700">{d.note}</p><p className="mt-6 border-t border-orange-200 pt-6 text-sm leading-6 text-slate-600">Route times shown during booking are estimates and can change with weather, road, ferry and terminal conditions.</p></aside></section>
  <section className="bg-[#211726] py-16 text-white"><div className="mx-auto max-w-[1180px] px-5"><div className="flex items-end justify-between gap-5"><div><p className="text-sm font-black uppercase tracking-[.18em] text-[#FF9E2F]">Popular routes</p><h2 className="mt-2 text-3xl font-black tracking-[-.035em] sm:text-5xl">Start with a proven connection.</h2></div><Route className="hidden text-[#FF8A05] sm:block" size={48}/></div><div className="mt-9 grid gap-3">{d.routes.map((r,i)=><a href="/#booking-search" key={r} className="flex items-center justify-between gap-4 rounded-2xl border border-white/15 px-5 py-5 hover:bg-white/5"><span className="flex items-center gap-4"><span className="text-sm font-black text-[#FF9E2F]">{String(i+1).padStart(2,"0")}</span><strong>{r}</strong></span><ArrowRight size={19}/></a>)}</div></div></section>
  <section className="mx-auto max-w-[1180px] px-5 py-16"><div className="grid items-center gap-8 rounded-[28px] bg-[#FF8A05] p-7 text-white md:grid-cols-[1fr_auto] md:p-10"><div><MapPin/><h2 className="mt-5 text-3xl font-black">Your exact pickup matters.</h2><p className="mt-2 max-w-xl text-white/85">Select the precise hotel, terminal, pier or address so Waydidi can calculate the route and show the right options.</p></div><a href="/#booking-search" className="rounded-full bg-white px-6 py-4 text-center font-black text-[#C96100]">Search vehicles</a></div></section>
  <PublicFooter/>
</main>}
