import { ArrowRight, Check, CircleHelp, MapPin, ShieldCheck } from "lucide-react";
import type { PublicPage } from "@/lib/public-content";
import { PublicFooter } from "@/components/public-footer";

export function MarketingPage({page}:{page:PublicPage}){const HeroIcon=page.icon;return <main className="bg-white text-[#211726]">
  <section className="mx-auto max-w-[1280px] px-5 pt-5 lg:px-8 lg:pt-8"><div className="relative overflow-hidden rounded-[30px] bg-[#FF8A05] px-6 py-14 text-white sm:px-10 lg:px-16 lg:py-20"><div className="absolute -right-16 -top-28 size-96 rounded-full border-[70px] border-white/10"/><div className="relative max-w-3xl"><span className="inline-flex size-14 items-center justify-center rounded-full bg-white/18"><HeroIcon size={27}/></span><p className="mt-8 text-sm font-black uppercase tracking-[.18em]">{page.eyebrow}</p><h1 className="mt-3 text-4xl font-black leading-[.98] tracking-[-.045em] sm:text-6xl lg:text-7xl">{page.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/90">{page.intro}</p><div className="mt-9 flex flex-wrap gap-3"><a href="/#booking-search" className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 font-black text-[#C96100]">Book a ride <ArrowRight size={18}/></a><a href="/contact" className="inline-flex items-center rounded-full border border-white/45 px-6 py-3.5 font-bold">Ask Waydidi</a></div></div></div></section>
  <section className="mx-auto grid max-w-[1180px] gap-4 px-5 py-14 md:grid-cols-3 lg:px-0">{page.highlights.map(item=>{const Icon=item.icon;return <article key={item.title} className="rounded-[24px] bg-[#F5F6F8] p-6"><span className="grid size-11 place-items-center rounded-full bg-[#FFF0DF] text-[#D96F00]"><Icon size={22}/></span><h2 className="mt-5 text-xl font-black">{item.title}</h2><p className="mt-2 leading-7 text-slate-600">{item.text}</p></article>})}</section>
  {page.sections.length>0&&<section className="mx-auto max-w-[980px] px-5 pb-16"><div className="space-y-4">{page.sections.map((s,i)=><article key={s.title} className="grid gap-4 border-t border-slate-200 py-8 md:grid-cols-[80px_1fr]"><div className="text-3xl font-black text-[#FF8A05]">{String(i+1).padStart(2,"0")}</div><div><h2 className="text-2xl font-black tracking-[-.025em]">{s.title}</h2><p className="mt-3 text-lg leading-8 text-slate-600">{s.body}</p>{s.bullets&&<ul className="mt-4 space-y-2">{s.bullets.map(b=><li key={b} className="flex gap-3"><Check className="mt-1 shrink-0 text-[#FF8A05]" size={18}/>{b}</li>)}</ul>}</div></article>)}</div></section>}
  {page.faq&&<section className="bg-[#F5F6F8] py-16"><div className="mx-auto max-w-[900px] px-5"><p className="text-sm font-black uppercase tracking-[.18em] text-[#D96F00]">Good to know</p><h2 className="mt-2 text-3xl font-black tracking-[-.035em] sm:text-4xl">Frequently asked questions</h2><div className="mt-8 space-y-3">{page.faq.map(item=><details key={item.q} className="group rounded-2xl bg-white px-5 py-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-black [&::-webkit-details-marker]:hidden">{item.q}<CircleHelp className="shrink-0 text-[#FF8A05]" size={20}/></summary><p className="mt-3 max-w-3xl leading-7 text-slate-600">{item.a}</p></details>)}</div></div></section>}
  <section className="mx-auto max-w-[1180px] px-5 py-16"><div className="grid items-center gap-8 rounded-[28px] bg-[#211726] p-7 text-white md:grid-cols-[1fr_auto] md:p-10"><div><div className="flex gap-3 text-[#FF8A05]"><ShieldCheck/><MapPin/></div><h2 className="mt-5 text-3xl font-black tracking-[-.03em]">Ready when your route is.</h2><p className="mt-2 text-white/70">Choose your pickup, destination and time to see available vehicles.</p></div><a href="/#booking-search" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#FF8A05] px-6 py-4 font-black">Search vehicles <ArrowRight size={18}/></a></div></section>
  <PublicFooter/>
</main>}
