// Every country dial code, Thailand first then A–Z. Flags live in /public/flags.
// Generated from the countries-list package (MIT); round flags from circle-flags (MIT).
export const COUNTRIES: [string, string, string][] = [
  ["th", "+66", "Thailand"],
  ["af", "+93", "Afghanistan"],
  ["ax", "+358", "Aland"],
  ["al", "+355", "Albania"],
  ["dz", "+213", "Algeria"],
  ["as", "+1684", "American Samoa"],
  ["ad", "+376", "Andorra"],
  ["ao", "+244", "Angola"],
  ["ai", "+1264", "Anguilla"],
  ["ag", "+1268", "Antigua and Barbuda"],
  ["ar", "+54", "Argentina"],
  ["am", "+374", "Armenia"],
  ["aw", "+297", "Aruba"],
  ["ac", "+247", "Ascension Island"],
  ["au", "+61", "Australia"],
  ["at", "+43", "Austria"],
  ["az", "+994", "Azerbaijan"],
  ["bs", "+1242", "Bahamas"],
  ["bh", "+973", "Bahrain"],
  ["bd", "+880", "Bangladesh"],
  ["bb", "+1246", "Barbados"],
  ["by", "+375", "Belarus"],
  ["be", "+32", "Belgium"],
  ["bz", "+501", "Belize"],
  ["bj", "+229", "Benin"],
  ["bm", "+1441", "Bermuda"],
  ["bt", "+975", "Bhutan"],
  ["bo", "+591", "Bolivia"],
  ["bq", "+5997", "Bonaire"],
  ["ba", "+387", "Bosnia and Herzegovina"],
  ["bw", "+267", "Botswana"],
  ["br", "+55", "Brazil"],
  ["io", "+246", "British Indian Ocean Territory"],
  ["vg", "+1284", "British Virgin Islands"],
  ["bn", "+673", "Brunei"],
  ["bg", "+359", "Bulgaria"],
  ["bf", "+226", "Burkina Faso"],
  ["bi", "+257", "Burundi"],
  ["cv", "+238", "Cabo Verde"],
  ["kh", "+855", "Cambodia"],
  ["cm", "+237", "Cameroon"],
  ["ca", "+1", "Canada"],
  ["ky", "+1345", "Cayman Islands"],
  ["cf", "+236", "Central African Republic"],
  ["td", "+235", "Chad"],
  ["cl", "+56", "Chile"],
  ["cn", "+86", "China"],
  ["cx", "+61", "Christmas Island"],
  ["cc", "+61", "Cocos (Keeling) Islands"],
  ["co", "+57", "Colombia"],
  ["km", "+269", "Comoros"],
  ["ck", "+682", "Cook Islands"],
  ["cr", "+506", "Costa Rica"],
  ["hr", "+385", "Croatia"],
  ["cu", "+53", "Cuba"],
  ["cw", "+5999", "Curacao"],
  ["cy", "+357", "Cyprus"],
  ["cz", "+420", "Czechia"],
  ["cd", "+243", "Democratic Republic of the Congo"],
  ["dk", "+45", "Denmark"],
  ["dj", "+253", "Djibouti"],
  ["dm", "+1767", "Dominica"],
  ["do", "+1809", "Dominican Republic"],
  ["tl", "+670", "East Timor"],
  ["ec", "+593", "Ecuador"],
  ["eg", "+20", "Egypt"],
  ["sv", "+503", "El Salvador"],
  ["gq", "+240", "Equatorial Guinea"],
  ["er", "+291", "Eritrea"],
  ["ee", "+372", "Estonia"],
  ["sz", "+268", "Eswatini"],
  ["et", "+251", "Ethiopia"],
  ["fk", "+500", "Falkland Islands"],
  ["fo", "+298", "Faroe Islands"],
  ["fj", "+679", "Fiji"],
  ["fi", "+358", "Finland"],
  ["fr", "+33", "France"],
  ["gf", "+594", "French Guiana"],
  ["pf", "+689", "French Polynesia"],
  ["ga", "+241", "Gabon"],
  ["gm", "+220", "Gambia"],
  ["ge", "+995", "Georgia"],
  ["de", "+49", "Germany"],
  ["gh", "+233", "Ghana"],
  ["gi", "+350", "Gibraltar"],
  ["gr", "+30", "Greece"],
  ["gl", "+299", "Greenland"],
  ["gd", "+1473", "Grenada"],
  ["gp", "+590", "Guadeloupe"],
  ["gu", "+1671", "Guam"],
  ["gt", "+502", "Guatemala"],
  ["gg", "+44", "Guernsey"],
  ["gn", "+224", "Guinea"],
  ["gw", "+245", "Guinea-Bissau"],
  ["gy", "+592", "Guyana"],
  ["ht", "+509", "Haiti"],
  ["hn", "+504", "Honduras"],
  ["hk", "+852", "Hong Kong"],
  ["hu", "+36", "Hungary"],
  ["is", "+354", "Iceland"],
  ["in", "+91", "India"],
  ["id", "+62", "Indonesia"],
  ["ir", "+98", "Iran"],
  ["iq", "+964", "Iraq"],
  ["ie", "+353", "Ireland"],
  ["im", "+44", "Isle of Man"],
  ["il", "+972", "Israel"],
  ["it", "+39", "Italy"],
  ["ci", "+225", "Ivory Coast"],
  ["jm", "+1876", "Jamaica"],
  ["jp", "+81", "Japan"],
  ["je", "+44", "Jersey"],
  ["jo", "+962", "Jordan"],
  ["kz", "+7", "Kazakhstan"],
  ["ke", "+254", "Kenya"],
  ["ki", "+686", "Kiribati"],
  ["xk", "+377", "Kosovo"],
  ["kw", "+965", "Kuwait"],
  ["kg", "+996", "Kyrgyzstan"],
  ["la", "+856", "Laos"],
  ["lv", "+371", "Latvia"],
  ["lb", "+961", "Lebanon"],
  ["ls", "+266", "Lesotho"],
  ["lr", "+231", "Liberia"],
  ["ly", "+218", "Libya"],
  ["li", "+423", "Liechtenstein"],
  ["lt", "+370", "Lithuania"],
  ["lu", "+352", "Luxembourg"],
  ["mo", "+853", "Macao"],
  ["mg", "+261", "Madagascar"],
  ["mw", "+265", "Malawi"],
  ["my", "+60", "Malaysia"],
  ["mv", "+960", "Maldives"],
  ["ml", "+223", "Mali"],
  ["mt", "+356", "Malta"],
  ["mh", "+692", "Marshall Islands"],
  ["mq", "+596", "Martinique"],
  ["mr", "+222", "Mauritania"],
  ["mu", "+230", "Mauritius"],
  ["yt", "+262", "Mayotte"],
  ["mx", "+52", "Mexico"],
  ["fm", "+691", "Micronesia"],
  ["md", "+373", "Moldova"],
  ["mc", "+377", "Monaco"],
  ["mn", "+976", "Mongolia"],
  ["me", "+382", "Montenegro"],
  ["ms", "+1664", "Montserrat"],
  ["ma", "+212", "Morocco"],
  ["mz", "+258", "Mozambique"],
  ["mm", "+95", "Myanmar"],
  ["na", "+264", "Namibia"],
  ["nr", "+674", "Nauru"],
  ["np", "+977", "Nepal"],
  ["nl", "+31", "Netherlands"],
  ["nc", "+687", "New Caledonia"],
  ["nz", "+64", "New Zealand"],
  ["ni", "+505", "Nicaragua"],
  ["ne", "+227", "Niger"],
  ["ng", "+234", "Nigeria"],
  ["nu", "+683", "Niue"],
  ["nf", "+672", "Norfolk Island"],
  ["kp", "+850", "North Korea"],
  ["mk", "+389", "North Macedonia"],
  ["mp", "+1670", "Northern Mariana Islands"],
  ["no", "+47", "Norway"],
  ["om", "+968", "Oman"],
  ["pk", "+92", "Pakistan"],
  ["pw", "+680", "Palau"],
  ["ps", "+970", "Palestine"],
  ["pa", "+507", "Panama"],
  ["pg", "+675", "Papua New Guinea"],
  ["py", "+595", "Paraguay"],
  ["pe", "+51", "Peru"],
  ["ph", "+63", "Philippines"],
  ["pn", "+64", "Pitcairn Islands"],
  ["pl", "+48", "Poland"],
  ["pt", "+351", "Portugal"],
  ["pr", "+1787", "Puerto Rico"],
  ["qa", "+974", "Qatar"],
  ["cg", "+242", "Republic of the Congo"],
  ["re", "+262", "Reunion"],
  ["ro", "+40", "Romania"],
  ["ru", "+7", "Russia"],
  ["rw", "+250", "Rwanda"],
  ["bl", "+590", "Saint Barthelemy"],
  ["sh", "+290", "Saint Helena"],
  ["kn", "+1869", "Saint Kitts and Nevis"],
  ["lc", "+1758", "Saint Lucia"],
  ["mf", "+590", "Saint Martin"],
  ["pm", "+508", "Saint Pierre and Miquelon"],
  ["vc", "+1784", "Saint Vincent and the Grenadines"],
  ["ws", "+685", "Samoa"],
  ["sm", "+378", "San Marino"],
  ["st", "+239", "Sao Tome and Principe"],
  ["sa", "+966", "Saudi Arabia"],
  ["sn", "+221", "Senegal"],
  ["rs", "+381", "Serbia"],
  ["sc", "+248", "Seychelles"],
  ["sl", "+232", "Sierra Leone"],
  ["sg", "+65", "Singapore"],
  ["sx", "+1721", "Sint Maarten"],
  ["sk", "+421", "Slovakia"],
  ["si", "+386", "Slovenia"],
  ["sb", "+677", "Solomon Islands"],
  ["so", "+252", "Somalia"],
  ["za", "+27", "South Africa"],
  ["gs", "+500", "South Georgia and the South Sandwich Islands"],
  ["kr", "+82", "South Korea"],
  ["ss", "+211", "South Sudan"],
  ["es", "+34", "Spain"],
  ["lk", "+94", "Sri Lanka"],
  ["sd", "+249", "Sudan"],
  ["sr", "+597", "Suriname"],
  ["sj", "+4779", "Svalbard and Jan Mayen"],
  ["se", "+46", "Sweden"],
  ["ch", "+41", "Switzerland"],
  ["sy", "+963", "Syria"],
  ["tw", "+886", "Taiwan"],
  ["tj", "+992", "Tajikistan"],
  ["tz", "+255", "Tanzania"],
  ["tg", "+228", "Togo"],
  ["tk", "+690", "Tokelau"],
  ["to", "+676", "Tonga"],
  ["tt", "+1868", "Trinidad and Tobago"],
  ["ta", "+290", "Tristan da Cunha"],
  ["tn", "+216", "Tunisia"],
  ["tm", "+993", "Turkmenistan"],
  ["tc", "+1649", "Turks and Caicos Islands"],
  ["tv", "+688", "Tuvalu"],
  ["tr", "+90", "T\u00fcrkiye"],
  ["vi", "+1340", "U.S. Virgin Islands"],
  ["ug", "+256", "Uganda"],
  ["ua", "+380", "Ukraine"],
  ["ae", "+971", "United Arab Emirates"],
  ["gb", "+44", "United Kingdom"],
  ["us", "+1", "United States"],
  ["uy", "+598", "Uruguay"],
  ["uz", "+998", "Uzbekistan"],
  ["vu", "+678", "Vanuatu"],
  ["va", "+379", "Vatican City"],
  ["ve", "+58", "Venezuela"],
  ["vn", "+84", "Vietnam"],
  ["wf", "+681", "Wallis and Futuna"],
  ["eh", "+212", "Western Sahara"],
  ["ye", "+967", "Yemen"],
  ["zm", "+260", "Zambia"],
  ["zw", "+263", "Zimbabwe"],
];

// Shared dial codes: the country a number most likely belongs to.
export const MAIN_COUNTRY: Record<string, string> = { "+1": "us", "+44": "gb", "+7": "ru", "+61": "au", "+47": "no", "+358": "fi", "+262": "re", "+590": "gp", "+599": "cw", "+212": "ma", "+290": "sh" };
