import type { LucideIcon } from "lucide-react";
import { BadgeCheck, BriefcaseBusiness, Building2, CarFront, CircleHelp, Clock3, Headphones, Luggage, MapPin, Plane, ReceiptText, RefreshCcw, Route, ShieldCheck, UserRoundCheck } from "lucide-react";

// Switch to "https://waydidi.com" once the domain is registered and pointed at this site.
// Canonical URLs, the sitemap and robots.txt all read from this value.
export const SITE_URL = "https://waydidi-private-transfer.dankbangkok.chatgpt.site";

export type InfoSection = { title: string; body: string; bullets?: string[] };
export type PublicPage = {
  slug: string; eyebrow: string; title: string; intro: string; icon: LucideIcon;
  highlights: { title: string; text: string; icon: LucideIcon }[];
  sections: InfoSection[]; faq?: { q: string; a: string }[];
};

export const publicPages: PublicPage[] = [
  { slug:"about", eyebrow:"About Waydidi", title:"Thailand, comfortably connected.", intro:"Waydidi arranges private, pre-booked rides with local drivers across Thailand. We focus on clear communication, practical vehicles and a calm door-to-door experience.", icon:CarFront,
    highlights:[{title:"Built around real journeys",text:"Airport arrivals, hotel transfers and long-distance travel planned as one connected service.",icon:Route},{title:"Local operations",text:"Routes and pickup details are handled with on-the-ground knowledge.",icon:MapPin},{title:"Human support",text:"A real person can help when travel plans change.",icon:Headphones}],
    sections:[{title:"Why Waydidi exists",body:"Getting between Thai cities, islands and airports should not require negotiating at the curb or coordinating several providers. Waydidi brings the route, vehicle, driver and booking record into one place."},{title:"How we work",body:"You choose a route and time, review the vehicle category and total, then receive one booking reference. Our operations view follows the ride from assignment through completion."},{title:"What we promise",body:"We aim to show the important details before you pay: route, pickup time, vehicle category, luggage allowance, payment terms and the rules that apply if plans change."}] },
  { slug:"contact", eyebrow:"Contact & support", title:"Help before, during and after your ride.", intro:"Use your booking reference when contacting us so we can find your journey quickly. For urgent pickup issues, include your current location and a phone number we can reach.", icon:Headphones,
    highlights:[{title:"Booking help",text:"Questions about routes, vehicles, luggage or changing a ride.",icon:CircleHelp},{title:"Day-of-travel support",text:"Help with meeting points, driver contact and delays.",icon:Clock3},{title:"After your journey",text:"Receipts, lost-property reports and refund requests.",icon:ReceiptText}],
    sections:[{title:"Contact Waydidi",body:"Email support@waydidi.com with your booking reference, travel date and a short description of what you need. If your pickup is within 24 hours, put “Urgent pickup” in the subject line."},{title:"Information to include",body:"Share only what helps us resolve the request: booking reference, passenger name, pickup date, pickup location and a reachable phone number. Never send full card details or passwords."},{title:"Response priorities",body:"Active journeys and pickups happening within 24 hours are handled first. Non-urgent policy, receipt and future-booking questions follow in order."}] },
  { slug:"faq", eyebrow:"Frequently asked questions", title:"Straight answers for a smoother ride.", intro:"The essentials about booking, meeting your driver, luggage, changes and payment—collected in one place.", icon:CircleHelp,
    highlights:[{title:"Before booking",text:"Choose a route, date, time, passengers and luggage.",icon:Route},{title:"At pickup",text:"Keep your phone available and meet at the confirmed point.",icon:MapPin},{title:"After booking",text:"Use Manage booking for eligible date, time and cancellation requests.",icon:RefreshCcw}], sections:[],
    faq:[{q:"When is my booking confirmed?",a:"Your ride is confirmed when Waydidi issues a booking reference and the confirmation page shows your journey details."},{q:"Can I change the pickup time?",a:"Eligible bookings can request a date or time change from Manage booking until three days before pickup. Changes depend on availability."},{q:"Can I cancel?",a:"You can submit a cancellation and refund request until 24 hours before pickup. Refunds require manual review and approval."},{q:"Where will I meet the driver at the airport?",a:"Your confirmation shows the pickup instructions. Keep your phone available after landing; the exact meeting point can vary by terminal."},{q:"What if my luggage does not fit?",a:"Select a vehicle that matches both passenger and luggage capacity. Contact support before travel for oversized items, sports gear or extra bags."},{q:"How do I check my ride?",a:"Open Manage booking and enter the booking reference together with the verification information requested."}] },
  { slug:"airport-transfer", eyebrow:"Airport transfers", title:"Land, meet your driver, and move on.", intro:"Pre-book a private airport pickup or drop-off with a confirmed time, vehicle category and meeting instructions.", icon:Plane,
    highlights:[{title:"Clear meeting point",text:"Pickup instructions are linked to your booking.",icon:MapPin},{title:"Flight details",text:"Add your flight number so operations can identify the correct arrival.",icon:Plane},{title:"Right-size vehicle",text:"Choose capacity for every passenger, suitcase and carry-on.",icon:Luggage}],
    sections:[{title:"Airport pickup",body:"Enter the airport or terminal as your pickup and your hotel or address as the destination. Add a flight number and a phone or WhatsApp contact that works after landing."},{title:"Airport drop-off",body:"Allow enough time for traffic, check-in and terminal changes. Your requested pickup time remains your responsibility; contact support if you are unsure how much buffer to allow."},{title:"Waiting and delays",body:"Flight information helps us understand arrival changes, but immigration, baggage and terminal disruptions can vary. Keep your phone connected and tell support when a major delay affects the meeting."}], faq:[{q:"Do you monitor my flight?",a:"When a valid flight number is supplied, operations can use it to identify arrival changes. You should still notify us about major itinerary changes."},{q:"Can I book for someone else?",a:"Yes. Enter the lead passenger’s name and reachable phone number, and keep the booking reference available."}] },
  { slug:"a-to-b-transfer", eyebrow:"A-to-B private transfer", title:"Your own car, straight from door to door.", intro:"Book a private ride between hotels, homes, offices, piers and attractions without sharing the vehicle with other passengers.", icon:MapPin,
    highlights:[{title:"Private vehicle",text:"The selected vehicle category is reserved for your party.",icon:CarFront},{title:"Upfront route",text:"Pickup and drop-off are recorded before checkout.",icon:Route},{title:"Door-to-door",text:"Use precise, vehicle-accessible addresses where possible.",icon:Building2}],
    sections:[{title:"Best for",body:"A-to-B transfers suit airport connections, hotel changes, meetings, family trips and any journey where timing and privacy matter."},{title:"Location accuracy",body:"Choose the exact place result and review its full address. For malls, resorts and large complexes, add the lobby, entrance or meeting point in your booking notes."},{title:"Route changes",body:"The quoted ride covers the confirmed pickup and drop-off. Extra stops, waiting or a material destination change may require a revised price and driver confirmation."}] },
  { slug:"long-journeys", eyebrow:"Long journeys", title:"Travel between Thai regions without changing cars.", intro:"A comfortable private alternative for intercity routes, remote resorts and journeys that are awkward by public transport.", icon:Route,
    highlights:[{title:"One continuous ride",text:"Keep your party and luggage together from start to finish.",icon:CarFront},{title:"Planned rest stops",text:"Ask the driver for a safe break on longer routes.",icon:Clock3},{title:"Regional coverage",text:"Request routes throughout Thailand, subject to driver availability.",icon:MapPin}],
    sections:[{title:"Planning a long route",body:"Use accurate pickup and destination pins, select a suitable vehicle and tell us about children, older travelers, mobility needs or bulky luggage before the ride."},{title:"Stops on the way",body:"Reasonable comfort stops can be discussed with your driver. Sightseeing stops, long waiting periods or route diversions must be agreed in advance and may change the price."},{title:"Weather and road conditions",body:"Travel times are estimates. Heavy rain, holiday traffic, ferry schedules and local road restrictions can affect the journey, so avoid tight onward connections."}] },
  { slug:"hourly-driver", eyebrow:"Hourly private driver", title:"Keep a driver and vehicle with you.", intro:"Designed for meetings, shopping, flexible city plans and several stops when a fixed A-to-B route is not enough.", icon:Clock3,
    highlights:[{title:"Time-based booking",text:"Reserve a block of hours instead of one fixed destination.",icon:Clock3},{title:"Multiple stops",text:"Build a practical sequence within the booked area and time.",icon:MapPin},{title:"Private throughout",text:"One vehicle remains assigned to your party.",icon:CarFront}],
    sections:[{title:"What is included",body:"Your selected vehicle and driver are reserved for the purchased duration, within the confirmed operating area and usage conditions shown at checkout."},{title:"How to plan stops",body:"Share the main itinerary before pickup. The driver can adapt the order when practical, but total time, road access, parking and operating-area limits still apply."},{title:"Extra time",body:"Additional hours are not automatic. They depend on driver availability and must be confirmed at the applicable rate before the original booking ends."}] },
  { slug:"cancellation-refund-policy", eyebrow:"Cancellation & refunds", title:"Clear rules when plans change.", intro:"Manage eligible bookings online, submit a cancellation request, and track the outcome with the same booking reference.", icon:RefreshCcw,
    highlights:[{title:"Change window",text:"Eligible date and time changes can be requested until three days before pickup.",icon:Clock3},{title:"Cancellation window",text:"Submit a refund request until 24 hours before pickup.",icon:RefreshCcw},{title:"Manual approval",text:"Refund requests are reviewed by Waydidi operations.",icon:UserRoundCheck}],
    sections:[{title:"Changing a booking",body:"Date and time requests must be submitted at least three days before pickup. The original ride remains in place until Waydidi confirms the change and any price difference."},{title:"Cancelling a booking",body:"A cancellation request can be submitted until 24 hours before the scheduled pickup. Submission does not itself complete a refund; an administrator reviews eligibility and payment status."},{title:"Refund timing",body:"After approval, funds are returned through the original payment method where supported. Bank and card-network processing times are outside Waydidi’s control. Cash bookings have no prepaid amount to refund."},{title:"Late cancellations and no-shows",body:"Requests inside 24 hours and missed pickups are normally non-refundable because driver and vehicle capacity has already been committed, except where required by law or where Waydidi cannot provide the service."}] },
  { slug:"luggage-policy", eyebrow:"Luggage policy", title:"Choose for your bags, not only your group.", intro:"Vehicle capacity covers both passengers and luggage. Accurate bag counts help prevent delays, unsafe loading and last-minute vehicle changes.", icon:Luggage,
    highlights:[{title:"Count every bag",text:"Include checked bags, cabin bags and large personal items.",icon:BriefcaseBusiness},{title:"Respect capacity",text:"Luggage must fit safely without blocking seats or visibility.",icon:ShieldCheck},{title:"Tell us about special items",text:"Declare wheelchairs, strollers, sports gear and oversized cases.",icon:CircleHelp}],
    sections:[{title:"Standard luggage",body:"Use the capacity shown on each vehicle card. A suitcase means a standard checked bag; a carry-on means a cabin-size bag or small backpack."},{title:"Oversized and special items",body:"Golf bags, surfboards, bicycles, musical instruments, mobility equipment and unusually large cases need advance confirmation. Measurements and a photo can help us match a vehicle."},{title:"Unsafe or undeclared luggage",body:"Drivers cannot carry items that prevent seatbelt use, obstruct the driver, exceed lawful limits or create a safety risk. An upgrade or additional vehicle may be required at extra cost."}] },
  { slug:"airport-pickup-instructions", eyebrow:"Airport pickup guide", title:"From arrivals hall to your driver.", intro:"A simple arrival checklist for meeting your Waydidi driver at Thailand’s airports.", icon:Plane,
    highlights:[{title:"Before flying",text:"Check the passenger phone number, flight number and arrival airport.",icon:BadgeCheck},{title:"After landing",text:"Connect your phone and check the booking instructions.",icon:Plane},{title:"At the meeting point",text:"Look for the confirmed sign name and verify the driver details.",icon:MapPin}],
    sections:[{title:"1. Before departure",body:"Review the booking confirmation and correct any flight, passenger or phone details before the change window closes. Save the booking reference offline."},{title:"2. After landing",body:"Turn on your phone, collect your bags and follow the terminal signs in your confirmation. If immigration or baggage is taking much longer than expected, message support."},{title:"3. Meet safely",body:"Match the driver name, vehicle information or Waydidi instruction before entering a vehicle. Do not accept an unverified replacement or share your booking reference with solicitors."},{title:"4. If you cannot connect",body:"Stay at the confirmed meeting area, avoid moving between terminals without telling support, and contact Waydidi with your booking reference and current landmark."}] },
  { slug:"safety-driver-standards", eyebrow:"Safety & driver standards", title:"Professional standards for every ride.", intro:"Waydidi’s operating rules cover driver identity, vehicle readiness, journey status evidence and respectful passenger care.", icon:ShieldCheck,
    highlights:[{title:"Verified assignment",text:"Only the driver assigned in operations should perform the ride.",icon:UserRoundCheck},{title:"Journey status",text:"Drivers confirm standby, pickup and completion through their secure link.",icon:BadgeCheck},{title:"Safe conduct",text:"Seatbelts, lawful driving and a roadworthy vehicle are expected.",icon:ShieldCheck}],
    sections:[{title:"Driver requirements",body:"Drivers must hold the licences and documents required for the vehicle and service, remain fit to drive, follow traffic law and treat passengers respectfully."},{title:"Vehicle readiness",body:"The vehicle should be clean, roadworthy, correctly insured for its use and suitable for the confirmed passenger and luggage count."},{title:"Operational confirmation",body:"Waydidi can require location permission and time-stamped journey photos at standby, pickup and drop-off. These records support dispatch, safety and dispute review."},{title:"Report a concern",body:"For immediate danger, contact local emergency services first. Then report the booking reference, time, location and a factual description to Waydidi support."}] },
];

export type DestinationRegion = "Bangkok & Central" | "East Coast & Islands" | "Gulf Coast" | "Andaman Coast";
export const destinationRegions: DestinationRegion[] = ["Bangkok & Central","East Coast & Islands","Gulf Coast","Andaman Coast"];
export type DestinationJourney = { title:string; time:string; text:string };
export type Destination = {
  slug:string; name:string; kicker:string; intro:string; color:string; highlights:string[]; routes:string[]; note:string; region:DestinationRegion;
  // Optional SEO content. The city page renders each section only when it is filled in.
  image?:string; h1?:string; seoTitle?:string; seoDescription?:string; areas?:string[]; journeys?:DestinationJourney[]; tips?:string[]; faq?:{ q:string; a:string }[]; nearby?:string[];
};
export const destinations: Destination[] = [
  {slug:"bangkok",region:"Bangkok & Central",
    h1:"Bangkok private transfers & airport taxi",
    seoTitle:"Bangkok Private Transfer & Airport Taxi | Waydidi",
    seoDescription:"Pre-book a private transfer in Bangkok. Suvarnabhumi and Don Mueang airport pickups, hotel-to-hotel rides and trips to Pattaya, Hua Hin and Ayutthaya.",
    areas:["Sukhumvit","Silom & Sathorn","Riverside","Siam & Pratunam","Khao San & Old Town","Chinatown (Yaowarat)","Ratchada & Ari","Bang Na","Suvarnabhumi Airport (BKK)","Don Mueang Airport (DMK)"],
    journeys:[
      {title:"Suvarnabhumi Airport ↔ Bangkok",time:"Usually 30–60 min",text:"The most common Bangkok transfer. Your driver meets you in the arrivals hall and takes you straight to your hotel, condo or office in the city."},
      {title:"Don Mueang Airport ↔ Bangkok",time:"Usually 30–60 min",text:"Don Mueang handles most budget flights. A private car is simpler than taxi queues, especially with a group or lots of luggage."},
      {title:"Suvarnabhumi ↔ Don Mueang",time:"Usually 45–75 min",text:"Connecting between Bangkok's two airports on separate tickets? Book one car for the transfer and allow plenty of time for check-in."},
      {title:"Bangkok → Pattaya",time:"Usually 2–2.5 hours",text:"A direct drive down the motorway to Pattaya, Jomtien or Naklua, with pickup from your Bangkok hotel or either airport."},
      {title:"Bangkok → Hua Hin",time:"Usually 3–3.5 hours",text:"Head south to Hua Hin or Cha-am in one private vehicle. A comfort stop along the way can be arranged."},
      {title:"Bangkok → Ayutthaya",time:"Usually 1–1.5 hours",text:"Reach the ancient capital's hotels and historic area without changing between trains, vans and tuk-tuks."},
    ],
    tips:[
      "Bangkok traffic changes a lot during the day. Weekday mornings (about 7–9:30) and evenings (about 16:30–19:30) are the slowest, and heavy rain can slow the whole city. For flights, plan to leave earlier than the typical drive time suggests.",
      "Many routes use Bangkok's elevated expressways, which are much faster than surface roads at busy times. Your quote is based on the route between your exact pickup and drop-off.",
      "For airport pickups, add your flight number when you book so we can follow your arrival. Your confirmation includes your meeting instructions and a way to contact us if you are delayed at immigration or baggage claim.",
      "Some hotels, condos and sois have narrow entrances or one-way access. Choosing the exact building in the search, rather than just a district, helps your driver reach the right door.",
    ],
    faq:[
      {q:"How long is the drive from Suvarnabhumi Airport to central Bangkok?",a:"Usually 30–60 minutes to areas like Sukhumvit, Silom or Siam. It can be longer during rush hours or heavy rain."},
      {q:"Can I book a transfer from Don Mueang Airport?",a:"Yes. Waydidi covers both Suvarnabhumi (BKK) and Don Mueang (DMK). Choose your airport as the pickup in the search."},
      {q:"Can you pick me up from my hotel or condo in Bangkok?",a:"Yes. Search for the exact hotel, condo or address as your pickup and your driver will come to that location."},
      {q:"Can I go from Bangkok straight to Pattaya or Hua Hin?",a:"Yes. One private car takes you door to door, so you do not need to change vehicles on the way."},
      {q:"What if my flight is delayed?",a:"Add your flight number when you book. If your plans change, contact Waydidi with your booking reference so we can help with your pickup."},
      {q:"What vehicle should I choose for my group?",a:"Pick a vehicle that fits both your passengers and your luggage. Larger groups or many suitcases usually need an SUV or minivan."},
    ],
    nearby:["pattaya","ayutthaya","hua-hin","kanchanaburi"],
name:"Bangkok",kicker:"Capital connections",intro:"Move between Bangkok’s airports, riverside hotels, business districts and neighbourhoods with a private driver.",color:"#40230f",highlights:["Suvarnabhumi and Don Mueang airport transfers","Sukhumvit, Silom, Sathorn and riverside hotels","Connections to Pattaya, Ayutthaya and Hua Hin"],routes:["Suvarnabhumi Airport → Bangkok","Bangkok → Pattaya","Bangkok → Ayutthaya"],note:"Allow extra time during weekday rush hours and major events."},
  {slug:"phuket",region:"Andaman Coast",name:"Phuket",kicker:"Island arrivals",intro:"Private transfers from Phuket International Airport to beach resorts, marinas and hotels across the island.",color:"#0f4c4c",highlights:["Airport pickups with meeting instructions","Patong, Kata, Karon, Bang Tao and Rawai","Pier and marina connections"],routes:["Phuket Airport → Patong","Phuket Airport → Kata","Phuket → Krabi"],note:"Travel times vary considerably between beaches and during peak arrival periods."},
  {slug:"krabi",region:"Andaman Coast",name:"Krabi",kicker:"Coast and cliffs",intro:"Connect Krabi Airport, Ao Nang, Krabi Town and mainland piers in one comfortable private ride.",color:"#345d36",highlights:["Krabi Airport arrivals","Ao Nang and Krabi Town hotels","Mainland pier drop-offs"],routes:["Krabi Airport → Ao Nang","Krabi → Phuket","Krabi → Khao Lak"],note:"For island connections, confirm the exact mainland pier and ferry time."},
  {slug:"pattaya",region:"East Coast & Islands",name:"Pattaya",kicker:"Easy eastern escape",intro:"Direct private transfers between Bangkok airports, Pattaya hotels, Jomtien and the Eastern Seaboard.",color:"#153c72",highlights:["Bangkok airport connections","Pattaya and Jomtien hotels","Laem Chabang and Rayong routes"],routes:["Suvarnabhumi Airport → Pattaya","Bangkok → Pattaya","Pattaya → Don Mueang Airport"],note:"Hotel entrances and beach-road traffic restrictions can affect the final meeting point."},
  {slug:"kanchanaburi",region:"Bangkok & Central",name:"Kanchanaburi",kicker:"River and history",intro:"Travel privately from Bangkok to Kanchanaburi’s town, riverside resorts and national-park gateways.",color:"#574322",highlights:["Bangkok hotel pickup","River Kwai area transfers","Flexible long-distance comfort stops"],routes:["Bangkok → Kanchanaburi","Suvarnabhumi Airport → Kanchanaburi","Kanchanaburi → Ayutthaya"],note:"Remote resorts may require precise map pins rather than a general district name."},
  {slug:"koh-chang",region:"East Coast & Islands",name:"Koh Chang",kicker:"The island road south",intro:"Plan the mainland drive, ferry crossing and Koh Chang resort drop-off as a connected journey.",color:"#0d5c58",highlights:["Trat Airport and Bangkok origins","Ferry-aware scheduling","Resort delivery on Koh Chang"],routes:["Bangkok → Koh Chang","Trat Airport → Koh Chang","Pattaya → Koh Chang"],note:"Ferry operating hours and queues can change the arrival estimate."},
  {slug:"koh-kood",region:"East Coast & Islands",name:"Koh Kood",kicker:"Remote island calm",intro:"Reach the correct Trat mainland pier for your Koh Kood boat connection with time to check in.",color:"#14666f",highlights:["Bangkok to Trat pier transfers","Trat Airport connections","Schedule built around your boat"],routes:["Bangkok → Laem Sok Pier","Trat Airport → Laem Sok Pier","Pattaya → Laem Sok Pier"],note:"Road transfers end at the mainland pier unless an island-side service is explicitly confirmed."},
  {slug:"ayutthaya",region:"Bangkok & Central",name:"Ayutthaya",kicker:"Ancient capital",intro:"A straightforward private transfer between Bangkok and Ayutthaya’s hotels, station and historic area.",color:"#6e3e24",highlights:["Bangkok and airport pickup","Hotel-to-hotel transfers","Connections onward to Kanchanaburi"],routes:["Bangkok → Ayutthaya","Don Mueang Airport → Ayutthaya","Ayutthaya → Kanchanaburi"],note:"Temple sightseeing is not included in a standard A-to-B transfer unless booked separately."},
  {slug:"hua-hin",region:"Gulf Coast",name:"Hua Hin",kicker:"Gulf-side comfort",intro:"Travel from Bangkok or the airports directly to Hua Hin, Cha-am and nearby beach resorts.",color:"#7a4c1e",highlights:["Bangkok airport transfers","Hua Hin and Cha-am resorts","Private family-friendly vehicles"],routes:["Bangkok → Hua Hin","Suvarnabhumi Airport → Hua Hin","Hua Hin → Pattaya"],note:"Weekend and holiday traffic can add substantial travel time south of Bangkok."},
];

export const termsPage: PublicPage = {slug:"terms",eyebrow:"Terms of service",title:"The terms behind every Waydidi ride.",intro:"These terms explain how bookings are confirmed, what passengers must provide, and how changes, delays and service issues are handled.",icon:ReceiptText,highlights:[{title:"Confirmed details",text:"Your reference records the route, date, time, vehicle and total.",icon:BadgeCheck},{title:"Accurate information",text:"Passenger, contact, flight and luggage details must be correct.",icon:CircleHelp},{title:"Fair resolution",text:"Operational changes are handled with an alternative or eligible refund.",icon:RefreshCcw}],sections:[{title:"Booking and payment",body:"A booking is confirmed only when Waydidi issues a booking reference. The confirmation records the selected service, route, pickup time, vehicle category, capacity, payment method and total. Prices may change before confirmation if route or booking details change."},{title:"Passenger responsibilities",body:"Provide accurate contact, pickup, flight, passenger and luggage information. Be ready at the confirmed place and time, keep your phone available and ensure everyone follows safety instructions. Undeclared oversized luggage or excess passengers may require a larger vehicle or prevent service."},{title:"Changes, cancellation and refunds",body:"Date and time requests are available until three days before pickup and remain subject to availability. Cancellation requests may be submitted until 24 hours before pickup. Refunds require manual approval and, where approved, return through the applicable original payment method."},{title:"Pickup, waiting and delays",body:"Travel and arrival times are estimates. Traffic, weather, immigration, baggage and ferry operations can affect timing. Material route changes, extra stops or waiting outside the confirmed service may require an additional charge."},{title:"Vehicle and service changes",body:"Waydidi may provide an equivalent or upgraded vehicle when the selected model is unavailable. If Waydidi cannot provide the confirmed service, the customer will be offered a reasonable alternative or an appropriate refund."},{title:"Liability and applicable law",body:"Waydidi is not responsible for losses caused by inaccurate customer information, unlawful requests, events outside reasonable control or missed onward travel where insufficient time was allowed. Mandatory rights under applicable Thai law are not excluded."}]};

export const privacyPage: PublicPage = {slug:"privacy",eyebrow:"Privacy & Thailand PDPA",title:"Your journey data, handled with care.",intro:"This notice explains what personal data Waydidi uses, why it is needed, who may receive it and how you can exercise your rights under Thailand’s PDPA.",icon:ShieldCheck,highlights:[{title:"Purpose limited",text:"We use booking data to quote, arrange, support and account for rides.",icon:BadgeCheck},{title:"Controlled access",text:"Only relevant staff, drivers and providers receive necessary details.",icon:UserRoundCheck},{title:"Your rights",text:"You may request access, correction, deletion or objection where applicable.",icon:ShieldCheck}],sections:[{title:"Data we collect",body:"This can include your name, email, phone number, route, map locations, schedule, passenger and luggage counts, flight details, pickup notes, special requests, booking activity, support messages and payment status. Driver operations may include location and journey evidence."},{title:"Why we use it",body:"We process information to provide quotes, confirm and perform contracts, dispatch drivers, communicate about journeys, prevent fraud, resolve disputes, meet accounting and legal duties, and improve service reliability. Where consent is required, you may withdraw it."},{title:"Payments and service providers",body:"Payment providers handle card or wallet credentials on their systems; Waydidi receives transaction status and references rather than full card details. We may use vetted hosting, email, mapping, analytics and support providers under appropriate instructions."},{title:"Sharing with drivers",body:"Assigned drivers receive only the trip and contact details needed to perform the journey. They must not reuse passenger data for unrelated purposes."},{title:"Retention and security",body:"Records are kept only as long as needed for operations, accounting, disputes, safety and legal requirements, then deleted or anonymised. Waydidi uses access controls, secure tokens, logging and private storage appropriate to the information."},{title:"Your PDPA rights",body:"Subject to legal limits, you may ask to access, correct, transfer, restrict, object to or delete personal data, and may complain to Thailand’s Personal Data Protection Committee. Contact support@waydidi.com and provide enough information to verify your identity."}]};
