"use client";
import { useEffect,useState } from "react";
import { Clock3,Save } from "lucide-react";
const names:Record<string,string>={economy_sedan:"Economy sedan",comfort_bmw:"Comfort BMW",comfort_suv:"Comfort SUV",premium_minivan:"Premium Minivan"};
type Rule={vehicleId:string;minimumHours:number;basePrice:number;additionalHourPrice:number;includedKmPerHour:number;extraPricePerKm:number};
export default function HourlyWorkspace(){const [areaId,setAreaId]=useState("ANY"),[areas,setAreas]=useState<Array<{id:string;name:string}>>([]),[rules,setRules]=useState<Rule[]>([]),[defaults,setDefaults]=useState<Record<string,Omit<Rule,"vehicleId">>>({}),[packages,setPackages]=useState<Array<Rule&{areaId:string}>>([]),[saved,setSaved]=useState("");
useEffect(()=>{fetch("/api/admin/hourly-pricing").then(r=>r.json()).then(data=>{setAreas(data.areas??[]);setDefaults(data.defaults??{});setPackages(data.packages??[]);setRules(Object.entries(data.defaults??{}).map(([vehicleId,value])=>({vehicleId,...value as Omit<Rule,"vehicleId">})));});},[]);
useEffect(()=>{if(!Object.keys(defaults).length)return;setRules(Object.entries(defaults).map(([vehicleId,value])=>({vehicleId,...value,...(packages.find(p=>p.areaId===areaId&&p.vehicleId===vehicleId)??{})})));},[areaId,defaults,packages]);
const update=(i:number,key:keyof Rule,value:string)=>setRules(current=>current.map((r,index)=>index===i?{...r,[key]:Number(value)}:r));
async function save(rule:Rule){setSaved("");const response=await fetch("/api/admin/hourly-pricing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...rule,areaId})});setSaved(response.ok?`${names[rule.vehicleId]} saved`:"Could not save package");if(response.ok)setPackages(current=>[...current.filter(p=>!(p.areaId===areaId&&p.vehicleId===rule.vehicleId)),{...rule,areaId}]);}
return <main className="min-h-screen bg-[#f4f6f8] text-[#211726]"><header className="bg-[#FF8A05] px-6 py-5 text-white"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="text-sm font-bold text-white/75">WAYDIDI OPERATIONS</p><h1 className="text-3xl font-black">Hourly pricing</h1></div><a href="/admin/pricing" className="rounded-full bg-white px-5 py-3 font-bold text-[#D96F00]">Area pricing</a></div></header><section className="mx-auto max-w-7xl p-6"><div className="mb-6 rounded-3xl bg-white p-6 shadow-sm"><label className="font-bold">Price area <select value={areaId} onChange={e=>setAreaId(e.target.value)} className="ml-3 rounded-xl border p-3"><option value="ANY">All Thailand (default)</option>{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><p className="mt-3 text-sm text-slate-500">Area-specific packages override the default when the pickup is inside that published map area.</p></div><div className="grid gap-5 lg:grid-cols-2">{rules.map((rule,i)=><article key={rule.vehicleId} className="rounded-3xl bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-orange-50 text-[#D96F00]"><Clock3/></span><h2 className="text-xl font-black">{names[rule.vehicleId]}</h2></div><div className="grid grid-cols-2 gap-4">{[["minimumHours","Minimum hours"],["basePrice","Package price (THB)"],["additionalHourPrice","Extra hour (THB)"],["includedKmPerHour","Included km/hour"],["extraPricePerKm","Extra km (THB)"]].map(([key,label])=><label key={key} className="text-sm font-bold text-slate-600">{label}<input type="number" value={rule[key as keyof Rule]} onChange={e=>update(i,key as keyof Rule,e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-slate-50 p-3 text-[#211726]"/></label>)}</div><button onClick={()=>save(rule)} className="mt-5 flex items-center gap-2 rounded-full bg-[#FF8A05] px-5 py-3 font-bold text-white"><Save size={17}/> Save package</button></article>)}</div>{saved&&<p className="fixed bottom-6 right-6 rounded-full bg-[#211726] px-5 py-3 font-bold text-white">{saved}</p>}</section></main>}
