"use client";
import Link from "next/link";
import { useState, useEffect, type FormEvent } from "react";
import { Building2, CalendarDays, FileText, Users, BadgePercent } from "lucide-react";
import { NewRideRequest } from "./new-request";
import { canBook, canFinance, thb, thaiToday, type PartnerRole } from "@/lib/partner-display";
import type { PartnerRate, PartnerProfile, commissionStatement } from "@/lib/partner-portal";
type Booking={reference:string;customerName:string;pickup:string;dropoff:string;pickupDate:string;pickupTime:string;vehicle:string;status:string;paymentStatus:string;totalMinor:number};
type Statement=Awaited<ReturnType<typeof commissionStatement>>;
type Invoice={id:string;bookingReference:string;amountMinor:number;createdAt:string};
const card="rounded-3xl border border-slate-200 bg-white p-5 sm:p-6",field="mt-1 w-full rounded-xl border border-slate-200 bg-white p-3",button="rounded-full bg-orange-500 px-5 py-3 font-semibold text-white disabled:opacity-50";
const label=(s:string)=>s.replaceAll("_"," ");
export function PartnerWorkspace({name,email,role,kind,rates,bookings,requests,profile,statement:initialStatement,invoices}:{name:string;email:string;role:PartnerRole;kind:string;rates:PartnerRate[];bookings:Booking[];requests:{token:string;status:string;note:string|null;expiresAt:string}[];profile:PartnerProfile|null;statement:Statement|null;invoices:Invoice[]}){
 const [tab,setTab]=useState("bookings"),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[date,setDate]=useState(""),[detail,setDetail]=useState<Record<string,unknown>|null>(null),[error,setError]=useState("");
 const [period,setPeriod]=useState(thaiToday().slice(0,7)),[statement,setStatement]=useState(initialStatement);
 const upcoming=bookings.filter(b=>b.pickupDate>=thaiToday()&&b.status==="confirmed");
 const visible=bookings.filter(b=>(!query||`${b.reference} ${b.customerName} ${b.pickup} ${b.dropoff}`.toLowerCase().includes(query.toLowerCase()))&&(!date||b.pickupDate===date)&&(filter==="all"||(filter==="upcoming"?b.pickupDate>=thaiToday()&&b.status==="confirmed":b.status===filter)));
 async function showBooking(ref:string){setError("");try{const r=await fetch(`/api/agency/bookings/${encodeURIComponent(ref)}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setDetail(d.booking);}catch(e){setError(e instanceof Error?e.message:"Could not load booking.");}}
 async function changeMonth(e:FormEvent){e.preventDefault();setError("");try{const r=await fetch(`/api/agency/statement?period=${encodeURIComponent(period)}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setStatement(d);}catch(e){setError(e instanceof Error?e.message:"Could not load statement.");}}
 return <main className="min-h-screen bg-[#F5F6F8] text-[#211726]"><div className="mx-auto max-w-7xl space-y-6 px-5 py-8 pb-28">
  <header className="flex flex-wrap items-end justify-between gap-5 rounded-3xl bg-[#211726] p-7 text-white sm:p-9"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-orange-300"><Building2 size={17}/>{kind==="hotel"?"Hotel & concierge":"Agency"} workspace</p><h1 className="mt-3 text-3xl font-bold sm:text-4xl">{name}</h1><p className="mt-3 text-sm text-white/70">{email} · {role} access</p></div><Link href="/contact" className="rounded-full border border-white/30 px-5 py-3 text-sm font-semibold">Partner support ↗</Link></header>
  <section className="grid gap-4 sm:grid-cols-3">{[{title:"Upcoming trips",value:upcoming.length,Icon:CalendarDays},{title:"Open requests",value:requests.filter(r=>r.status==="submitted"||r.expiresAt>new Date().toISOString()).length,Icon:FileText},{title:"Active rates",value:rates.length,Icon:BadgePercent}].map(({title,value,Icon})=><div className={card} key={title}><Icon className="mb-4 text-orange-500" size={23}/><p className="text-sm text-slate-500">{title}</p><p className="mt-1 text-3xl font-bold">{value}</p></div>)}</section>
  {canBook(role)&&<NewRideRequest rates={rates}/>}
  <nav aria-label="Partner workspace" className="flex gap-2 overflow-x-auto">{["bookings","rates",...(canFinance(role)?["finance"]:[]),...(role==="admin"?["team"]:[])].map(t=><button key={t} type="button" aria-current={tab===t?"page":undefined} onClick={()=>{setTab(t);setError("");}} className={`rounded-full px-6 py-3 text-sm font-semibold capitalize ${tab===t?"bg-orange-500 text-white":"bg-white text-slate-600"}`}>{t}</button>)}</nav>
  <p role="alert" className="text-sm text-red-700">{error}</p>
  {tab==="bookings"&&<>
   {requests.length>0&&<section className={card}><h2 className="text-xl font-bold">Requests awaiting confirmation</h2><p className="mt-1 text-sm text-slate-500">Operations reviews availability. A request does not reserve a vehicle.</p><div className="mt-4 divide-y">{requests.map(r=><div className="flex flex-wrap items-center justify-between gap-3 py-3" key={r.token}><div><p className="font-semibold">{r.note||"Guest transfer request"}</p><p className="text-sm text-slate-500">{r.status==="submitted"?"Awaiting operations review":r.expiresAt<new Date().toISOString()?"Link expired":"Guest details needed"}</p></div>{r.status==="waiting"&&r.expiresAt>new Date().toISOString()&&canBook(role)&&<Link className="text-sm font-semibold text-orange-700 underline" href={`/f/${r.token}`}>Enter guest details</Link>}</div>)}</div></section>}
   <section className={card}><h2 className="text-xl font-bold">Partner bookings</h2><div className="my-5 grid gap-3 md:grid-cols-[1fr_auto_auto]"><label><span className="sr-only">Search bookings</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Reference, guest or route" className="w-full rounded-xl border p-3"/></label><label><span className="sr-only">Pickup date</span><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="w-full rounded-xl border p-3"/></label><label><span className="sr-only">Booking status</span><select value={filter} onChange={e=>setFilter(e.target.value)} className="w-full rounded-xl border p-3"><option value="all">All statuses</option><option value="upcoming">Upcoming confirmed</option>{["confirmed","completed","cancelled","pending_payment"].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-slate-500"><tr>{["Booking / guest","Pickup (Thailand)","Route","Status","Total",""].map(h=><th key={h} className="border-b p-3 font-medium">{h}</th>)}</tr></thead><tbody>{visible.map(b=><tr key={b.reference} className="border-b"><td className="p-3"><button className="font-bold text-orange-700 underline" onClick={()=>void showBooking(b.reference)}>{b.reference}</button><p>{b.customerName}</p></td><td className="p-3">{b.pickupDate}<p className="text-slate-500">{b.pickupTime}</p></td><td className="max-w-xs p-3">{b.pickup} → {b.dropoff}<p className="text-xs text-slate-500">{b.vehicle}</p></td><td className="p-3"><span className="rounded-lg bg-slate-100 px-2 py-1 capitalize">{label(b.status)}</span><p className="mt-2 text-xs text-slate-500">{label(b.paymentStatus)}</p></td><td className="whitespace-nowrap p-3">{thb(b.totalMinor)}</td><td className="p-3">{["confirmed","completed"].includes(b.status)&&<a href={`/api/agency/bookings/${b.reference}/pdf`} className="font-semibold text-orange-700">PDF</a>}</td></tr>)}</tbody></table>{!visible.length&&<p className="p-8 text-center text-slate-500">No bookings match your search.</p>}</div><p className="mt-4 text-xs text-slate-500">Latest {bookings.length} bookings, up to 300. Contact operations for older records.</p>
   </section>{detail&&<section className={card}><div className="flex justify-between"><h2 className="text-xl font-bold">Booking {String(detail.reference)}</h2><button onClick={()=>setDetail(null)} aria-label="Close booking details">✕</button></div><dl className="mt-5 grid gap-4 sm:grid-cols-2">{Object.entries(detail).filter(([k])=>k!=="reference").map(([key,value])=><div key={key}><dt className="text-xs font-semibold capitalize text-slate-500">{key.replace(/([A-Z])/g," $1")}</dt><dd className="mt-1 whitespace-pre-wrap text-sm">{String(value??"—")}</dd></div>)}</dl><p className="mt-5 text-sm text-slate-500">For itinerary changes or cancellation, contact partner support with the booking reference.</p></section>}
  </>}
  {tab==="rates"&&<section className={card}><h2 className="text-xl font-bold">Your negotiated rates</h2><p className="mt-2 text-sm text-slate-500">One journey per rate. Extras and availability need confirmation. Select a rate in New ride request to lock its route and vehicle.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{rates.map(r=><article className="rounded-2xl border p-5" key={r.id}><p className="text-xs uppercase text-orange-700">{r.service_type}{r.booked_hours?` · ${r.booked_hours} hours`:""}</p><h3 className="mt-2 text-lg font-bold">{r.label}</h3><p className="my-3 text-sm text-slate-600">{r.pickup} → {r.dropoff}<br/>{label(r.vehicle)}</p><p className="text-2xl font-bold">{thb(r.price_minor)}</p><p className="mt-3 text-xs text-slate-500">Pickup dates {r.valid_from}–{r.valid_until}</p></article>)}</div>{!rates.length&&<p className="py-8 text-slate-500">No agreed rates yet. Send a custom request or contact partnerships.</p>}</section>}
  {tab==="finance"&&canFinance(role)&&<>
   <section className={card}><h2 className="text-xl font-bold">Commission statement</h2><p className="mt-2 text-sm text-slate-500">Earned on completed, fully paid trips, excluding extras. Refunds reduce earnings. Cash requires a recorded receipt. Historical bookings without agreed terms earn no automatic commission.</p><form onSubmit={e=>void changeMonth(e)} className="my-5 flex flex-wrap gap-3"><label><span className="sr-only">Statement month</span><input type="month" required value={period} onChange={e=>setPeriod(e.target.value)} className="rounded-xl border p-3"/></label><button className={button}>View month</button>{statement&&<a className="rounded-full border px-5 py-3 font-semibold" href={`/api/agency/statement?period=${statement.period}&format=csv`}>Download CSV</a>}</form>{statement&&<><div className="grid gap-3 sm:grid-cols-3">{[{title:"Earned",amount:statement.earnedMinor},{title:"Paid",amount:statement.paidMinor},{title:"Balance / adjustment",amount:statement.balanceMinor}].map(({title,amount})=><div className="rounded-xl bg-slate-50 p-4" key={title}><p className="text-xs text-slate-500">{title}</p><p className="mt-1 text-xl font-bold">{thb(amount)}</p></div>)}</div><ul className="mt-4 divide-y">{statement.rows.map(r=><li key={r.reference} className="flex justify-between gap-3 py-3 text-sm"><span>{r.reference} · {r.pickup_date} · {label(r.status)}</span><strong>{thb(r.commissionMinor)}</strong></li>)}</ul>{!statement.rows.length&&<p className="mt-4 text-slate-500">No commission entries for this month.</p>}</>}
   </section><section className={card}><h2 className="text-xl font-bold">Invoices</h2><p className="mt-2 text-sm text-slate-500">Issued by Waydidi finance. Open an invoice to print or save as PDF.</p><div className="mt-5 divide-y">{invoices.map(i=><a key={i.id} href={`/api/agency/invoices/${i.id}`} target="_blank" rel="noreferrer" className="flex flex-wrap justify-between gap-3 py-4 text-sm"><span><b>{i.bookingReference}</b> · {i.createdAt.slice(0,10)}</span><span className="font-bold text-orange-700">{thb(i.amountMinor)} · Open invoice ↗</span></a>)}</div>{!invoices.length&&<p className="mt-4 text-slate-500">No invoices yet. Ask finance with your booking reference.</p>}</section><section className={card}><h2 className="text-xl font-bold">Billing details</h2><p className="mt-3 whitespace-pre-wrap text-sm text-slate-600">{profile?.billing_name||name}<br/>{profile?.billing_address||"Billing address not configured"}<br/>{profile?.tax_id&&`Tax ID: ${profile.tax_id}`}<br/>Agreed commission: {(profile?.commission_bps??0)/100}%</p><p className="mt-3 text-sm text-slate-500">Contact partnerships to update your billing details or agreement.</p></section>
  </>}
  {tab==="team"&&role==="admin"&&<PartnerTeam/>}
 </div></main>;
}
function PartnerTeam(){
 const [members,setMembers]=useState<{email:string;role:PartnerRole;active:number}[]>([]),[primary,setPrimary]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/agency/team",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setMembers(d.members);setPrimary(d.primaryEmail);}
 useEffect(()=>{const timer=setTimeout(()=>void load().catch(e=>setError(e.message)),0);return()=>clearTimeout(timer);},[]);
 async function save(email:string,role:PartnerRole,active:boolean){setBusy(true);setError("");try{const r=await fetch("/api/agency/team",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,role,active})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();}catch(e){setError(e instanceof Error?e.message:"Could not save team access.");}finally{setBusy(false);}}
 return <section className={card}><h2 className="flex items-center gap-2 text-xl font-bold"><Users size={22}/>Team access</h2><p className="mt-2 text-sm text-slate-500">Primary administrator: {primary}. Members sign in using their verified work email. Adding an email enables access after verification; no invitation email is sent.</p><form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void save(String(d.get("email")),d.get("role") as PartnerRole,true);}} className="my-5 grid gap-3 md:grid-cols-[1fr_auto_auto]"><label>Work email<input name="email" type="email" required className={field}/></label><label>Role<select name="role" className={field}>{["booker","finance","viewer","admin"].map(r=><option key={r}>{r}</option>)}</select></label><button disabled={busy} className={`${button} self-end`}>Add / update member</button></form><p role="alert" className="text-sm text-red-700">{error}</p><p className="text-xs text-slate-500">Booker: requests and trips. Finance: trips and finances. Viewer: trips only. Admin: all partner functions and team access.</p><ul className="mt-4 divide-y">{members.map(m=><li key={m.email} className="flex flex-wrap justify-between gap-3 py-4 text-sm"><span>{m.email} · {m.role} · {m.active?"Active":"Disabled"}</span><button disabled={busy} onClick={()=>void save(m.email,m.role,!m.active)} className="font-bold text-orange-700">{m.active?"Disable access":"Enable access"}</button></li>)}</ul></section>;
}
