"use client";
import { FormEvent, useEffect, useState } from "react";
import { CalendarClock, CarFront, CheckCircle2, Clock3, History, LogOut, RefreshCw, Search, ShieldCheck, TicketX } from "lucide-react";
type Booking={reference:string;status:string;pickup:string;dropoff:string;pickupDate:string;pickupTime:string;passengers:number;luggage:number;vehicle:string;total:number;paymentMethod:string;serviceType:string;bookedHours:number|null;refundStatus:string|null;cancellationReason:string|null;bookingVersion:number};
type Change={id:string;changeType:string;reason:string|null;createdAt:string};
type ManageData={booking:Booking;eligibility:{canReschedule:boolean;canCancel:boolean};changes:Change[]};
type Tab="details"|"reschedule"|"cancel"|"activity";
export default function BookingLookup(){
 const [reference,setReference]=useState(""),[email,setEmail]=useState(""),[data,setData]=useState<ManageData|null>(null),[tab,setTab]=useState<Tab>("details"),[error,setError]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(false),[date,setDate]=useState(""),[time,setTime]=useState("09:00"),[reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false);
 async function load(){const r=await fetch("/api/bookings/manage",{cache:"no-store"});if(!r.ok){setData(null);return;}const value=await r.json() as ManageData;setData(value);setDate(value.booking.pickupDate);setTime(value.booking.pickupTime);}
 useEffect(()=>{load().catch(()=>undefined);},[]);
 async function signIn(e:FormEvent){e.preventDefault();setLoading(true);setError("");const r=await fetch("/api/bookings/manage/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reference,email})});const value=await r.json() as {error?:string};setLoading(false);if(!r.ok){setError(value.error??"Booking could not be opened.");return;}await load();}
 async function action(path:string,body:Record<string,unknown>){setLoading(true);setError("");setMessage("");const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const value=await r.json() as {error?:string;refundStatus?:string};setLoading(false);if(!r.ok){setError(value.error??"The change could not be completed.");return;}await load();setMessage(path.endsWith("cancel")?(value.refundStatus==="not_required"?"Your booking has been cancelled.":"Your booking is cancelled and the refund has started."):"Your pickup date and time have been updated.");}
 async function signOut(){await fetch("/api/bookings/manage/session",{method:"DELETE"});setData(null);setReference("");setEmail("");}
 if(!data)return <main className="min-h-[calc(100vh-102px)] bg-slate-50 px-5 py-12 text-[#211726]"><section className="mx-auto max-w-md rounded-[28px] border border-slate-200 bg-white p-7 shadow-sm"><span className="grid size-12 place-items-center rounded-full bg-orange-50 text-[#D96F00]"><ShieldCheck/></span><h1 className="mt-5 text-3xl font-black tracking-[-.04em]">Manage your booking</h1><p className="mt-3 leading-7 text-slate-600">Enter your booking reference and the email used at checkout.</p><form onSubmit={signIn} className="mt-7 space-y-5"><label className="block text-sm font-bold">Booking reference<input required value={reference} onChange={e=>setReference(e.target.value.toUpperCase())} placeholder="WD-1A2B3C4D5E6F" className="mt-2 h-13 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-base uppercase outline-none focus:border-[#FF8A05]"/></label><label className="block text-sm font-bold">Booking email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@email.com" className="mt-2 h-13 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-base outline-none focus:border-[#FF8A05]"/></label>{error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}<button disabled={loading} className="flex h-13 w-full items-center justify-center gap-2 rounded-full bg-[#FF8A05] font-bold text-white disabled:opacity-60"><Search size={18}/>{loading?"Opening…":"Open booking"}</button></form></section></main>;
 const b=data.booking;const tabs:[Tab,string,typeof CarFront][]=[["details","Booking details",CarFront],["reschedule","Change date & time",CalendarClock],["cancel","Cancel & refund",TicketX],["activity","Activity",History]];
 const cancellationText=b.status==="cancelled"?(b.refundStatus?`This booking is cancelled. Refund status: ${b.refundStatus.replaceAll("_"," ")}.`:"This booking is cancelled."):"Online cancellation is closed. Contact Waydidi support.";
 return <main className="min-h-[calc(100vh-102px)] bg-[#f4f6f8] px-4 py-8 text-[#211726] sm:px-6 lg:py-12"><div className="mx-auto max-w-6xl"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-[.15em] text-[#D96F00]">Booking {b.reference}</p><h1 className="mt-1 text-3xl font-black tracking-[-.04em] sm:text-4xl">Manage your journey</h1></div><button onClick={signOut} className="flex items-center gap-2 rounded-full border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold"><LogOut size={16}/>Close securely</button></div>{message&&<div className="mb-5 flex items-center gap-3 rounded-2xl bg-emerald-100 p-4 font-semibold text-emerald-800"><CheckCircle2/>{message}</div>}{error&&<div role="alert" className="mb-5 rounded-2xl bg-red-50 p-4 font-semibold text-red-700">{error}</div>}<div className="grid gap-6 lg:grid-cols-[270px_1fr]"><aside className="rounded-3xl bg-[#211726] p-3 text-white lg:sticky lg:top-[126px] lg:self-start"><div className="mb-2 rounded-2xl bg-white/10 p-4"><p className="text-xs font-bold uppercase tracking-wider text-white/60">Current status</p><p className="mt-1 text-lg font-black capitalize">{b.status.replaceAll("_"," ")}</p></div><nav className="flex gap-2 overflow-x-auto lg:grid">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>{setTab(id);setError("");setMessage("");}} className={`flex shrink-0 items-center gap-3 rounded-2xl px-4 py-3.5 text-left font-bold ${tab===id?"bg-[#FF8A05]":"text-white/75 hover:bg-white/10"}`}><Icon size={19}/>{label}</button>)}</nav></aside><section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
 {tab==="details"&&<><Heading icon={CarFront} title="Booking details"/><div className="mt-7 grid gap-6 sm:grid-cols-2"><Detail label="Pickup" value={b.pickup}/><Detail label="Drop-off" value={b.dropoff}/><Detail label="Date & time" value={`${b.pickupDate} at ${b.pickupTime}`}/><Detail label="Vehicle" value={b.vehicle}/><Detail label="Travelers" value={`${b.passengers} passengers · ${b.luggage} bags`}/><Detail label="Service" value={b.serviceType==="hourly"?`${b.bookedHours}-hour private driver`:"Private transfer"}/></div><div className="mt-8 flex items-end justify-between border-t border-slate-200 pt-6"><span className="font-bold text-slate-500">Booking total</span><strong className="text-3xl">฿{b.total.toLocaleString()}</strong></div></>}
 {tab==="reschedule"&&<><Heading icon={CalendarClock} title="Change date & time"/><p className="mt-3 text-slate-600">Changes are available until 72 hours before your current pickup. Your route, vehicle and price stay the same.</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="font-bold">New pickup date<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-2 h-13 w-full rounded-xl border border-slate-200 bg-slate-50 px-4"/></label><label className="font-bold">New pickup time<select value={time} onChange={e=>setTime(e.target.value)} className="mt-2 h-13 w-full rounded-xl border border-slate-200 bg-slate-50 px-4">{times().map(t=><option key={t}>{t}</option>)}</select></label></div>{!data.eligibility.canReschedule&&<Policy text="Online changes are closed for this booking. Contact Waydidi for assistance."/>}<button disabled={!data.eligibility.canReschedule||loading||(date===b.pickupDate&&time===b.pickupTime)} onClick={()=>action("/api/bookings/manage/reschedule",{pickupDate:date,pickupTime:time,bookingVersion:b.bookingVersion})} className="mt-7 flex h-13 items-center gap-2 rounded-full bg-[#FF8A05] px-7 font-bold text-white disabled:opacity-40"><RefreshCw size={18}/>{loading?"Updating…":"Confirm new schedule"}</button></>}
 {tab==="cancel"&&<><Heading icon={TicketX} title="Cancel & refund"/><p className="mt-3 text-slate-600">Online cancellation is available until 24 hours before pickup. Eligible card payments receive a full refund; cash bookings are simply cancelled.</p><div className="mt-6 rounded-2xl bg-slate-50 p-5"><div className="flex justify-between gap-4"><span>Refund amount</span><strong>{b.paymentMethod==="cash"?"No payment collected":`฿${b.total.toLocaleString()}`}</strong></div></div>{(data.eligibility.canCancel&&b.status==="confirmed")?<><label className="mt-6 block font-bold">Reason for cancellation<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={300} rows={4} placeholder="Tell us why you need to cancel" className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 p-4"/></label><label className="mt-5 flex items-start gap-3 rounded-2xl border border-slate-200 p-4 font-semibold"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-1 size-5 accent-[#FF8A05]"/>I understand that cancelling will release my vehicle and driver.</label><button disabled={loading||!confirmed||reason.trim().length<3} onClick={()=>action("/api/bookings/manage/cancel",{reason,confirmed,bookingVersion:b.bookingVersion})} className="mt-6 h-13 rounded-full bg-red-600 px-7 font-bold text-white disabled:opacity-40">{loading?"Cancelling…":"Cancel booking"}</button></>:<Policy text={cancellationText}/>}</>}
 {tab==="activity"&&<><Heading icon={History} title="Booking activity"/><div className="mt-7 space-y-4">{data.changes.length?data.changes.map(change=><article key={change.id} className="flex gap-4 border-b border-slate-100 pb-4"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-orange-50 text-[#D96F00]"><Clock3 size={18}/></span><div><p className="font-black capitalize">{change.changeType.replaceAll("_"," ")}</p><p className="mt-1 text-sm text-slate-500">{new Date(change.createdAt).toLocaleString("en-GB",{timeZone:"Asia/Bangkok",dateStyle:"medium",timeStyle:"short"})}</p>{change.reason&&<p className="mt-2 text-slate-600">{change.reason}</p>}</div></article>):<p className="rounded-2xl bg-slate-50 p-6 text-slate-500">No customer changes have been made.</p>}</div></>}
 </section></div></div></main>;
}
function Heading({icon:Icon,title}:{icon:typeof CarFront;title:string}){return <div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-full bg-orange-50 text-[#D96F00]"><Icon/></span><h2 className="text-2xl font-black">{title}</h2></div>}
function Detail({label,value}:{label:string;value:string}){return <div><p className="text-xs font-black uppercase tracking-[.13em] text-slate-400">{label}</p><p className="mt-2 font-bold leading-6">{value}</p></div>}
function Policy({text}:{text:string}){return <p className="mt-6 rounded-2xl bg-amber-50 p-4 font-semibold text-amber-900">{text}</p>}
function times(){return Array.from({length:96},(_,i)=>`${String(Math.floor(i/4)).padStart(2,"0")}:${String(i%4*15).padStart(2,"0")}`)}
